<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Hoofdstuk 4 Data exploratie en beschrijvende statistiek | Cursus Statistiek 2020-2021</title>
  <meta name="description" content="Basiscursus Statistiek voor de 2de Bachelor of Science in de Biologie, - in de Biochemie &amp; de Biotechnologie, - in de Biomedische Wetenschappen, en - in de Chemie" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Hoofdstuk 4 Data exploratie en beschrijvende statistiek | Cursus Statistiek 2020-2021" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Basiscursus Statistiek voor de 2de Bachelor of Science in de Biologie, - in de Biochemie &amp; de Biotechnologie, - in de Biomedische Wetenschappen, en - in de Chemie" />
  <meta name="github-repo" content="statOmics/statistiek2deBach" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Hoofdstuk 4 Data exploratie en beschrijvende statistiek | Cursus Statistiek 2020-2021" />
  
  <meta name="twitter:description" content="Basiscursus Statistiek voor de 2de Bachelor of Science in de Biologie, - in de Biochemie &amp; de Biotechnologie, - in de Biomedische Wetenschappen, en - in de Chemie" />
  

<meta name="author" content="Lieven Clement" />


<meta name="date" content="2020-11-13" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="chap-design.html"/>
<link rel="next" href="chap-besluit.html"/>
<script src="libs/header-attrs-2.4/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Cursus Statistiek 2020-2021</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Woord vooraf</a></li>
<li class="chapter" data-level="" data-path="links.html"><a href="links.html"><i class="fa fa-check"></i>Links</a></li>
<li class="chapter" data-level="1" data-path="inleiding.html"><a href="inleiding.html"><i class="fa fa-check"></i><b>1</b> Inleiding</a>
<ul>
<li class="chapter" data-level="1.1" data-path="inleiding.html"><a href="inleiding.html#sec:wetMeth"><i class="fa fa-check"></i><b>1.1</b> De Wetenschappelijke Methode</a></li>
<li class="chapter" data-level="1.2" data-path="inleiding.html"><a href="inleiding.html#boutade-met-statistiek-kan-je-alles-bewijzen"><i class="fa fa-check"></i><b>1.2</b> Boutade: met statistiek kan je alles bewijzen</a></li>
<li class="chapter" data-level="1.3" data-path="inleiding.html"><a href="inleiding.html#opzet-van-de-cursus"><i class="fa fa-check"></i><b>1.3</b> Opzet van de cursus</a></li>
<li class="chapter" data-level="1.4" data-path="inleiding.html"><a href="inleiding.html#case-study-oksel-microbiome"><i class="fa fa-check"></i><b>1.4</b> Case study: oksel microbiome</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="inleiding.html"><a href="inleiding.html#experimenteel-design-proefopzet"><i class="fa fa-check"></i><b>1.4.1</b> Experimenteel design (proefopzet)</a></li>
<li class="chapter" data-level="1.4.2" data-path="inleiding.html"><a href="inleiding.html#data-exploratie-en-beschrijvende-statistiek"><i class="fa fa-check"></i><b>1.4.2</b> Data exploratie en beschrijvende statistiek</a></li>
<li class="chapter" data-level="1.4.3" data-path="inleiding.html"><a href="inleiding.html#statistische-besluitvorming"><i class="fa fa-check"></i><b>1.4.3</b> Statistische Besluitvorming</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="inleiding.html"><a href="inleiding.html#case-study-ii-verschil-in-lengte-tussen-vrouwen-en-mannen"><i class="fa fa-check"></i><b>1.5</b> Case Study II: Verschil in lengte tussen vrouwen en mannen</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="inleiding.html"><a href="inleiding.html#experiment"><i class="fa fa-check"></i><b>1.5.1</b> Experiment</a></li>
<li class="chapter" data-level="1.5.2" data-path="inleiding.html"><a href="inleiding.html#herhaal-het-experiment"><i class="fa fa-check"></i><b>1.5.2</b> Herhaal het experiment</a></li>
<li class="chapter" data-level="1.5.3" data-path="inleiding.html"><a href="inleiding.html#herhaal-het-experiment-opnieuw"><i class="fa fa-check"></i><b>1.5.3</b> Herhaal het experiment opnieuw</a></li>
<li class="chapter" data-level="1.5.4" data-path="inleiding.html"><a href="inleiding.html#samenvatting"><i class="fa fa-check"></i><b>1.5.4</b> Samenvatting</a></li>
<li class="chapter" data-level="1.5.5" data-path="inleiding.html"><a href="inleiding.html#controle-van-beslissingsfouten"><i class="fa fa-check"></i><b>1.5.5</b> Controle van beslissingsfouten</a></li>
<li class="chapter" data-level="1.5.6" data-path="inleiding.html"><a href="inleiding.html#conclusies"><i class="fa fa-check"></i><b>1.5.6</b> Conclusies</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="inleiding.html"><a href="inleiding.html#case-study-salk-vaccin"><i class="fa fa-check"></i><b>1.6</b> Case study: Salk vaccin</a>
<ul>
<li class="chapter" data-level="1.6.1" data-path="inleiding.html"><a href="inleiding.html#nfip-study"><i class="fa fa-check"></i><b>1.6.1</b> NFIP Study</a></li>
<li class="chapter" data-level="1.6.2" data-path="inleiding.html"><a href="inleiding.html#confounding"><i class="fa fa-check"></i><b>1.6.2</b> Confounding</a></li>
<li class="chapter" data-level="1.6.3" data-path="inleiding.html"><a href="inleiding.html#salk-study"><i class="fa fa-check"></i><b>1.6.3</b> Salk Study</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="inleiding.html"><a href="inleiding.html#rol-van-statistiek"><i class="fa fa-check"></i><b>1.7</b> Rol van Statistiek</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="belangrijke-concepten-conventies.html"><a href="belangrijke-concepten-conventies.html"><i class="fa fa-check"></i><b>2</b> Belangrijke concepten &amp; conventies</a>
<ul>
<li class="chapter" data-level="2.1" data-path="belangrijke-concepten-conventies.html"><a href="belangrijke-concepten-conventies.html#inleiding-1"><i class="fa fa-check"></i><b>2.1</b> Inleiding</a></li>
<li class="chapter" data-level="2.2" data-path="belangrijke-concepten-conventies.html"><a href="belangrijke-concepten-conventies.html#variabelen"><i class="fa fa-check"></i><b>2.2</b> Variabelen</a></li>
<li class="chapter" data-level="2.3" data-path="belangrijke-concepten-conventies.html"><a href="belangrijke-concepten-conventies.html#subsec:pop"><i class="fa fa-check"></i><b>2.3</b> Populatie</a></li>
<li class="chapter" data-level="2.4" data-path="belangrijke-concepten-conventies.html"><a href="belangrijke-concepten-conventies.html#toevalsveranderlijken-of-toevallige-veranderlijken"><i class="fa fa-check"></i><b>2.4</b> Toevalsveranderlijken (of toevallige veranderlijken)</a></li>
<li class="chapter" data-level="2.5" data-path="belangrijke-concepten-conventies.html"><a href="belangrijke-concepten-conventies.html#beschrijven-van-de-populatie"><i class="fa fa-check"></i><b>2.5</b> Beschrijven van de populatie</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="belangrijke-concepten-conventies.html"><a href="belangrijke-concepten-conventies.html#intermezzo-probabiliteitstheorie"><i class="fa fa-check"></i><b>2.5.1</b> Intermezzo probabiliteitstheorie</a></li>
<li class="chapter" data-level="2.5.2" data-path="belangrijke-concepten-conventies.html"><a href="belangrijke-concepten-conventies.html#standardisatie"><i class="fa fa-check"></i><b>2.5.2</b> Standardisatie</a></li>
<li class="chapter" data-level="2.5.3" data-path="belangrijke-concepten-conventies.html"><a href="belangrijke-concepten-conventies.html#subsec:normalcalc"><i class="fa fa-check"></i><b>2.5.3</b> Achtergrond Normale verdeling</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="belangrijke-concepten-conventies.html"><a href="belangrijke-concepten-conventies.html#steekproef"><i class="fa fa-check"></i><b>2.6</b> Steekproef</a></li>
<li class="chapter" data-level="2.7" data-path="belangrijke-concepten-conventies.html"><a href="belangrijke-concepten-conventies.html#nhanes-gender"><i class="fa fa-check"></i><b>2.7</b> NHANES: Gender</a></li>
<li class="chapter" data-level="2.8" data-path="belangrijke-concepten-conventies.html"><a href="belangrijke-concepten-conventies.html#nhanes-lengte"><i class="fa fa-check"></i><b>2.8</b> NHANES: Lengte</a>
<ul>
<li class="chapter" data-level="2.8.1" data-path="belangrijke-concepten-conventies.html"><a href="belangrijke-concepten-conventies.html#empirische-distributie"><i class="fa fa-check"></i><b>2.8.1</b> Empirische distributie</a></li>
<li class="chapter" data-level="2.8.2" data-path="belangrijke-concepten-conventies.html"><a href="belangrijke-concepten-conventies.html#normale-benadering"><i class="fa fa-check"></i><b>2.8.2</b> Normale benadering</a></li>
<li class="chapter" data-level="2.8.3" data-path="belangrijke-concepten-conventies.html"><a href="belangrijke-concepten-conventies.html#referentie-intervallen"><i class="fa fa-check"></i><b>2.8.3</b> Referentie intervallen</a></li>
<li class="chapter" data-level="2.8.4" data-path="belangrijke-concepten-conventies.html"><a href="belangrijke-concepten-conventies.html#conclusions"><i class="fa fa-check"></i><b>2.8.4</b> Conclusions</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="belangrijke-concepten-conventies.html"><a href="belangrijke-concepten-conventies.html#statistieken"><i class="fa fa-check"></i><b>2.9</b> Statistieken</a></li>
<li class="chapter" data-level="2.10" data-path="belangrijke-concepten-conventies.html"><a href="belangrijke-concepten-conventies.html#conventie"><i class="fa fa-check"></i><b>2.10</b> Conventie</a></li>
<li class="chapter" data-level="2.11" data-path="belangrijke-concepten-conventies.html"><a href="belangrijke-concepten-conventies.html#code-voor-dit-hoofdstuk"><i class="fa fa-check"></i><b>2.11</b> Code voor dit hoofdstuk</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chap-design.html"><a href="chap-design.html"><i class="fa fa-check"></i><b>3</b> Studiedesign</a>
<ul>
<li class="chapter" data-level="3.1" data-path="chap-design.html"><a href="chap-design.html#inleiding-2"><i class="fa fa-check"></i><b>3.1</b> Inleiding</a></li>
<li class="chapter" data-level="3.2" data-path="chap-design.html"><a href="chap-design.html#sec:steekproefdesigns"><i class="fa fa-check"></i><b>3.2</b> Steekproefdesigns</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="chap-design.html"><a href="chap-design.html#replicatie"><i class="fa fa-check"></i><b>3.2.1</b> Replicatie</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="chap-design.html"><a href="chap-design.html#experimentele-studies"><i class="fa fa-check"></i><b>3.3</b> Experimentele studies</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="chap-design.html"><a href="chap-design.html#de-salk-vaccin-veldstudie"><i class="fa fa-check"></i><b>3.3.1</b> De Salk Vaccin Veldstudie</a></li>
<li class="chapter" data-level="3.3.2" data-path="chap-design.html"><a href="chap-design.html#gerandomiseerde-gecontroleerde-studies"><i class="fa fa-check"></i><b>3.3.2</b> Gerandomiseerde gecontroleerde studies</a></li>
<li class="chapter" data-level="3.3.3" data-path="chap-design.html"><a href="chap-design.html#parallelle-designs"><i class="fa fa-check"></i><b>3.3.3</b> Parallelle designs</a></li>
<li class="chapter" data-level="3.3.4" data-path="chap-design.html"><a href="chap-design.html#cross-over-designs"><i class="fa fa-check"></i><b>3.3.4</b> Cross-over designs</a></li>
<li class="chapter" data-level="3.3.5" data-path="chap-design.html"><a href="chap-design.html#factoriële-designs"><i class="fa fa-check"></i><b>3.3.5</b> Factoriële designs</a></li>
<li class="chapter" data-level="3.3.6" data-path="chap-design.html"><a href="chap-design.html#quasi-experimentele-designs"><i class="fa fa-check"></i><b>3.3.6</b> Quasi-experimentele designs</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="chap-design.html"><a href="chap-design.html#sec:observational"><i class="fa fa-check"></i><b>3.4</b> Observationele studies</a></li>
<li class="chapter" data-level="3.5" data-path="chap-design.html"><a href="chap-design.html#subsec:design:prosp"><i class="fa fa-check"></i><b>3.5</b> Prospectieve studies</a></li>
<li class="chapter" data-level="3.6" data-path="chap-design.html"><a href="chap-design.html#subsec:design:retro"><i class="fa fa-check"></i><b>3.6</b> Retrospectieve studies</a></li>
<li class="chapter" data-level="3.7" data-path="chap-design.html"><a href="chap-design.html#niet-gecontroleerde-studies"><i class="fa fa-check"></i><b>3.7</b> Niet-gecontroleerde studies</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="chap-design.html"><a href="chap-design.html#subsec:prepost"><i class="fa fa-check"></i><b>3.7.1</b> Pre-test/Post-test studies</a></li>
<li class="chapter" data-level="3.7.2" data-path="chap-design.html"><a href="chap-design.html#cross-sectionele-surveys"><i class="fa fa-check"></i><b>3.7.2</b> Cross-sectionele surveys</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="chap-describe.html"><a href="chap-describe.html"><i class="fa fa-check"></i><b>4</b> Data exploratie en beschrijvende statistiek</a>
<ul>
<li class="chapter" data-level="4.1" data-path="chap-describe.html"><a href="chap-describe.html#inleiding-3"><i class="fa fa-check"></i><b>4.1</b> Inleiding</a></li>
<li class="chapter" data-level="4.2" data-path="chap-describe.html"><a href="chap-describe.html#sec:univar"><i class="fa fa-check"></i><b>4.2</b> Univariate beschrijving van de variabelen</a></li>
<li class="chapter" data-level="4.3" data-path="chap-describe.html"><a href="chap-describe.html#sec:summarize"><i class="fa fa-check"></i><b>4.3</b> Samenvattingsmaten voor continue variabelen</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="chap-describe.html"><a href="chap-describe.html#maten-voor-de-centrale-ligging"><i class="fa fa-check"></i><b>4.3.1</b> Maten voor de centrale ligging</a></li>
<li class="chapter" data-level="4.3.2" data-path="chap-describe.html"><a href="chap-describe.html#subsec:spreiding"><i class="fa fa-check"></i><b>4.3.2</b> Spreidingsmaten</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="chap-describe.html"><a href="chap-describe.html#sec:normal"><i class="fa fa-check"></i><b>4.4</b> De Normale benadering van gegevens</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="chap-describe.html"><a href="chap-describe.html#sec:qq"><i class="fa fa-check"></i><b>4.4.1</b> QQ-plots</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="chap-describe.html"><a href="chap-describe.html#sec:explCatVar"><i class="fa fa-check"></i><b>4.5</b> Samenvattingsmaten voor categorische variabelen</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="chap-describe.html"><a href="chap-describe.html#prospectieve-studies-en-lukrake-steekproeven"><i class="fa fa-check"></i><b>4.5.1</b> Prospectieve studies en lukrake steekproeven</a></li>
<li class="chapter" data-level="4.5.2" data-path="chap-describe.html"><a href="chap-describe.html#subsec:retrospect"><i class="fa fa-check"></i><b>4.5.2</b> Retrospectieve studies</a></li>
<li class="chapter" data-level="4.5.3" data-path="chap-describe.html"><a href="chap-describe.html#rates-versus-risicos"><i class="fa fa-check"></i><b>4.5.3</b> Rates versus risico’s</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="chap-describe.html"><a href="chap-describe.html#associaties-tussen-twee-variabelen"><i class="fa fa-check"></i><b>4.6</b> Associaties tussen twee variabelen</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="chap-describe.html"><a href="chap-describe.html#subsec:kruistabel"><i class="fa fa-check"></i><b>4.6.1</b> Associatie tussen twee kwalitatieve variabelen</a></li>
<li class="chapter" data-level="4.6.2" data-path="chap-describe.html"><a href="chap-describe.html#subsec:asskwalcont"><i class="fa fa-check"></i><b>4.6.2</b> Associatie tussen één kwalitatieve en één continue variabele</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="chap-describe.html"><a href="chap-describe.html#sec:correlatie"><i class="fa fa-check"></i><b>4.7</b> Associatie tussen twee continue variabelen</a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="chap-describe.html"><a href="chap-describe.html#covariantie-en-correlatie"><i class="fa fa-check"></i><b>4.7.1</b> Covariantie en Correlatie</a></li>
<li class="chapter" data-level="4.7.2" data-path="chap-describe.html"><a href="chap-describe.html#pearson-correlatie"><i class="fa fa-check"></i><b>4.7.2</b> Pearson Correlatie</a></li>
<li class="chapter" data-level="4.7.3" data-path="chap-describe.html"><a href="chap-describe.html#verschillende-groottes-van-correlatie"><i class="fa fa-check"></i><b>4.7.3</b> Verschillende groottes van correlatie</a></li>
<li class="chapter" data-level="4.7.4" data-path="chap-describe.html"><a href="chap-describe.html#spearman-correlatie"><i class="fa fa-check"></i><b>4.7.4</b> Spearman correlatie</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="chap-describe.html"><a href="chap-describe.html#sec:missing"><i class="fa fa-check"></i><b>4.8</b> Onvolledige gegevens</a></li>
<li class="chapter" data-level="4.9" data-path="chap-describe.html"><a href="chap-describe.html#clips-over-de-code-in-dit-hoofdstuk"><i class="fa fa-check"></i><b>4.9</b> Clips over de code in dit hoofdstuk</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="chap-besluit.html"><a href="chap-besluit.html"><i class="fa fa-check"></i><b>5</b> Statistische besluitvorming</a>
<ul>
<li class="chapter" data-level="5.1" data-path="chap-besluit.html"><a href="chap-besluit.html#inleiding-4"><i class="fa fa-check"></i><b>5.1</b> Inleiding</a></li>
<li class="chapter" data-level="5.2" data-path="chap-besluit.html"><a href="chap-besluit.html#captopril-voorbeeld"><i class="fa fa-check"></i><b>5.2</b> Captopril voorbeeld</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="chap-besluit.html"><a href="chap-besluit.html#proefopzet"><i class="fa fa-check"></i><b>5.2.1</b> Proefopzet</a></li>
<li class="chapter" data-level="5.2.2" data-path="chap-besluit.html"><a href="chap-besluit.html#data-exploratie-beschrijvende-statistiek"><i class="fa fa-check"></i><b>5.2.2</b> Data Exploratie &amp; Beschrijvende Statistiek</a></li>
<li class="chapter" data-level="5.2.3" data-path="chap-besluit.html"><a href="chap-besluit.html#schatten"><i class="fa fa-check"></i><b>5.2.3</b> Schatten</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="chap-besluit.html"><a href="chap-besluit.html#puntschatters-het-steekproefgemiddelde"><i class="fa fa-check"></i><b>5.3</b> Puntschatters: het steekproefgemiddelde</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="chap-besluit.html"><a href="chap-besluit.html#overzicht"><i class="fa fa-check"></i><b>5.3.1</b> Overzicht</a></li>
<li class="chapter" data-level="5.3.2" data-path="chap-besluit.html"><a href="chap-besluit.html#het-steekproefgemiddelde-is-onvertekend"><i class="fa fa-check"></i><b>5.3.2</b> Het steekproefgemiddelde is onvertekend</a></li>
<li class="chapter" data-level="5.3.3" data-path="chap-besluit.html"><a href="chap-besluit.html#imprecisiestandard-error"><i class="fa fa-check"></i><b>5.3.3</b> Imprecisie/standard error</a></li>
<li class="chapter" data-level="5.3.4" data-path="chap-besluit.html"><a href="chap-besluit.html#subsec:verdelingXbar"><i class="fa fa-check"></i><b>5.3.4</b> Verdeling van het steekproefgemiddelde</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="chap-besluit.html"><a href="chap-besluit.html#intervalschatters"><i class="fa fa-check"></i><b>5.4</b> Intervalschatters</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="chap-besluit.html"><a href="chap-besluit.html#subsec:bigek"><i class="fa fa-check"></i><b>5.4.1</b> Gekende variantie op de metingen</a></li>
<li class="chapter" data-level="5.4.2" data-path="chap-besluit.html"><a href="chap-besluit.html#sec:tBI"><i class="fa fa-check"></i><b>5.4.2</b> Ongekende variantie op de metingen</a></li>
<li class="chapter" data-level="5.4.3" data-path="chap-besluit.html"><a href="chap-besluit.html#subsec:interpretBI"><i class="fa fa-check"></i><b>5.4.3</b> Interpretatie van betrouwbaarheidsintervallen</a></li>
<li class="chapter" data-level="5.4.4" data-path="chap-besluit.html"><a href="chap-besluit.html#wat-rapporteren"><i class="fa fa-check"></i><b>5.4.4</b> Wat rapporteren?</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="chap-besluit.html"><a href="chap-besluit.html#principe-van-hypothesetoetsen-via-one-sample-t-test"><i class="fa fa-check"></i><b>5.5</b> Principe van Hypothesetoetsen (via one sample t-test)</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="chap-besluit.html"><a href="chap-besluit.html#introductie-d.m.v.-captopril-voorbeeld"><i class="fa fa-check"></i><b>5.5.1</b> Introductie d.m.v. captopril voorbeeld</a></li>
<li class="chapter" data-level="5.5.2" data-path="chap-besluit.html"><a href="chap-besluit.html#hypotheses"><i class="fa fa-check"></i><b>5.5.2</b> Hypotheses</a></li>
<li class="chapter" data-level="5.5.3" data-path="chap-besluit.html"><a href="chap-besluit.html#test-statistiek"><i class="fa fa-check"></i><b>5.5.3</b> Test-statistiek</a></li>
<li class="chapter" data-level="5.5.4" data-path="chap-besluit.html"><a href="chap-besluit.html#de-p-waarde"><i class="fa fa-check"></i><b>5.5.4</b> De p-waarde</a></li>
<li class="chapter" data-level="5.5.5" data-path="chap-besluit.html"><a href="chap-besluit.html#kritieke-waarde"><i class="fa fa-check"></i><b>5.5.5</b> Kritieke waarde</a></li>
<li class="chapter" data-level="5.5.6" data-path="chap-besluit.html"><a href="chap-besluit.html#beslissingsfouten"><i class="fa fa-check"></i><b>5.5.6</b> Beslissingsfouten</a></li>
<li class="chapter" data-level="5.5.7" data-path="chap-besluit.html"><a href="chap-besluit.html#conclusies-captopril-voorbeeld."><i class="fa fa-check"></i><b>5.5.7</b> Conclusies Captopril voorbeeld.</a></li>
<li class="chapter" data-level="5.5.8" data-path="chap-besluit.html"><a href="chap-besluit.html#eenzijdig-of-tweezijdig-toetsen"><i class="fa fa-check"></i><b>5.5.8</b> Eenzijdig of tweezijdig toetsen?</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="chap-besluit.html"><a href="chap-besluit.html#geclusterde-metingen"><i class="fa fa-check"></i><b>5.6</b> Geclusterde metingen</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="chap-besluit.html"><a href="chap-besluit.html#captopril"><i class="fa fa-check"></i><b>5.6.1</b> Captopril</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="chap-besluit.html"><a href="chap-besluit.html#two-sample-t-test"><i class="fa fa-check"></i><b>5.7</b> Two-sample t-test</a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="chap-besluit.html"><a href="chap-besluit.html#notatie"><i class="fa fa-check"></i><b>5.7.1</b> Notatie</a></li>
<li class="chapter" data-level="5.7.2" data-path="chap-besluit.html"><a href="chap-besluit.html#oksel-voorbeeld"><i class="fa fa-check"></i><b>5.7.2</b> Oksel-voorbeeld</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="chap-besluit.html"><a href="chap-besluit.html#aannames"><i class="fa fa-check"></i><b>5.8</b> Aannames</a>
<ul>
<li class="chapter" data-level="5.8.1" data-path="chap-besluit.html"><a href="chap-besluit.html#nagaan-van-de-veronderstelling-van-normaliteit"><i class="fa fa-check"></i><b>5.8.1</b> Nagaan van de veronderstelling van Normaliteit</a></li>
<li class="chapter" data-level="5.8.2" data-path="chap-besluit.html"><a href="chap-besluit.html#nagaan-van-homoscedasticiteit"><i class="fa fa-check"></i><b>5.8.2</b> Nagaan van homoscedasticiteit</a></li>
</ul></li>
<li class="chapter" data-level="5.9" data-path="chap-besluit.html"><a href="chap-besluit.html#wat-rapporteren-1"><i class="fa fa-check"></i><b>5.9</b> Wat rapporteren?</a>
<ul>
<li class="chapter" data-level="5.9.1" data-path="chap-besluit.html"><a href="chap-besluit.html#reden-1-relatie-toetsen-en-betrouwbaarheidsintervallen"><i class="fa fa-check"></i><b>5.9.1</b> Reden 1: Relatie toetsen en betrouwbaarheidsintervallen</a></li>
<li class="chapter" data-level="5.9.2" data-path="chap-besluit.html"><a href="chap-besluit.html#reden-2-statistische-significantie-versus-wetenschappelijke-relevantie"><i class="fa fa-check"></i><b>5.9.2</b> Reden 2: Statistische significantie versus wetenschappelijke relevantie</a></li>
</ul></li>
<li class="chapter" data-level="5.10" data-path="chap-besluit.html"><a href="chap-besluit.html#equivalentie-intervallen"><i class="fa fa-check"></i><b>5.10</b> Equivalentie-intervallen</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="chap-linReg.html"><a href="chap-linReg.html"><i class="fa fa-check"></i><b>6</b> Enkelvoudige lineaire regressie</a>
<ul>
<li class="chapter" data-level="6.1" data-path="chap-linReg.html"><a href="chap-linReg.html#inleiding-5"><i class="fa fa-check"></i><b>6.1</b> Inleiding</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="chap-linReg.html"><a href="chap-linReg.html#borstkanker-dataset"><i class="fa fa-check"></i><b>6.1.1</b> Borstkanker dataset</a></li>
<li class="chapter" data-level="6.1.2" data-path="chap-linReg.html"><a href="chap-linReg.html#data-exploratie"><i class="fa fa-check"></i><b>6.1.2</b> Data exploratie</a></li>
<li class="chapter" data-level="6.1.3" data-path="chap-linReg.html"><a href="chap-linReg.html#model"><i class="fa fa-check"></i><b>6.1.3</b> Model</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="chap-linReg.html"><a href="chap-linReg.html#lineaire-regressie"><i class="fa fa-check"></i><b>6.2</b> Lineaire regressie</a></li>
<li class="chapter" data-level="6.3" data-path="chap-linReg.html"><a href="chap-linReg.html#parameterschatting"><i class="fa fa-check"></i><b>6.3</b> Parameterschatting</a></li>
<li class="chapter" data-level="6.4" data-path="chap-linReg.html"><a href="chap-linReg.html#sec:linBesluit"><i class="fa fa-check"></i><b>6.4</b> Statistische besluitvorming</a></li>
<li class="chapter" data-level="6.5" data-path="chap-linReg.html"><a href="chap-linReg.html#nagaan-van-modelveronderstellingen"><i class="fa fa-check"></i><b>6.5</b> Nagaan van modelveronderstellingen</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="chap-linReg.html"><a href="chap-linReg.html#lineariteit"><i class="fa fa-check"></i><b>6.5.1</b> Lineariteit</a></li>
<li class="chapter" data-level="6.5.2" data-path="chap-linReg.html"><a href="chap-linReg.html#veronderstelling-van-homoscedasticiteit-gelijkheid-van-variantie"><i class="fa fa-check"></i><b>6.5.2</b> Veronderstelling van homoscedasticiteit (gelijkheid van variantie)</a></li>
<li class="chapter" data-level="6.5.3" data-path="chap-linReg.html"><a href="chap-linReg.html#veronderstelling-van-normaliteit"><i class="fa fa-check"></i><b>6.5.3</b> Veronderstelling van normaliteit</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="chap-linReg.html"><a href="chap-linReg.html#afwijkingen-van-modelveronderstellingen"><i class="fa fa-check"></i><b>6.6</b> Afwijkingen van Modelveronderstellingen</a></li>
<li class="chapter" data-level="6.7" data-path="chap-linReg.html"><a href="chap-linReg.html#besluitvorming-over-gemiddelde-uitkomst"><i class="fa fa-check"></i><b>6.7</b> Besluitvorming over gemiddelde uitkomst</a></li>
<li class="chapter" data-level="6.8" data-path="chap-linReg.html"><a href="chap-linReg.html#predictie-intervallen"><i class="fa fa-check"></i><b>6.8</b> Predictie-intervallen</a>
<ul>
<li class="chapter" data-level="6.8.1" data-path="chap-linReg.html"><a href="chap-linReg.html#nhanes-voorbeeld"><i class="fa fa-check"></i><b>6.8.1</b> NHANES voorbeeld</a></li>
</ul></li>
<li class="chapter" data-level="6.9" data-path="chap-linReg.html"><a href="chap-linReg.html#sec:linAnova"><i class="fa fa-check"></i><b>6.9</b> Kwadratensommen en Anova-tabel</a>
<ul>
<li class="chapter" data-level="6.9.1" data-path="chap-linReg.html"><a href="chap-linReg.html#determinatie-coëfficiënt"><i class="fa fa-check"></i><b>6.9.1</b> Determinatie-coëfficiënt</a></li>
<li class="chapter" data-level="6.9.2" data-path="chap-linReg.html"><a href="chap-linReg.html#f-testen-in-het-enkelvoudig-lineair-regressiemodel"><i class="fa fa-check"></i><b>6.9.2</b> F-Testen in het enkelvoudig lineair regressiemodel</a></li>
<li class="chapter" data-level="6.9.3" data-path="chap-linReg.html"><a href="chap-linReg.html#anova-tabel"><i class="fa fa-check"></i><b>6.9.3</b> Anova Tabel</a></li>
</ul></li>
<li class="chapter" data-level="6.10" data-path="chap-linReg.html"><a href="chap-linReg.html#sec:linDummy"><i class="fa fa-check"></i><b>6.10</b> Dummy variabelen</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="chap-anova.html"><a href="chap-anova.html"><i class="fa fa-check"></i><b>7</b> Variantie analyse</a>
<ul>
<li class="chapter" data-level="7.1" data-path="chap-anova.html"><a href="chap-anova.html#inleiding-6"><i class="fa fa-check"></i><b>7.1</b> Inleiding</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="chap-anova.html"><a href="chap-anova.html#prostacycline-voorbeeld"><i class="fa fa-check"></i><b>7.1.1</b> Prostacycline voorbeeld</a></li>
<li class="chapter" data-level="7.1.2" data-path="chap-anova.html"><a href="chap-anova.html#model-1"><i class="fa fa-check"></i><b>7.1.2</b> Model</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="chap-anova.html"><a href="chap-anova.html#variantie-analyse"><i class="fa fa-check"></i><b>7.2</b> Variantie-analyse</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="chap-anova.html"><a href="chap-anova.html#model-2"><i class="fa fa-check"></i><b>7.2.1</b> Model</a></li>
<li class="chapter" data-level="7.2.2" data-path="chap-anova.html"><a href="chap-anova.html#kwadratensommen-en-anova"><i class="fa fa-check"></i><b>7.2.2</b> Kwadratensommen en Anova</a></li>
<li class="chapter" data-level="7.2.3" data-path="chap-anova.html"><a href="chap-anova.html#anova-test"><i class="fa fa-check"></i><b>7.2.3</b> Anova-test</a></li>
<li class="chapter" data-level="7.2.4" data-path="chap-anova.html"><a href="chap-anova.html#anova-tabel-1"><i class="fa fa-check"></i><b>7.2.4</b> Anova Tabel</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="chap-anova.html"><a href="chap-anova.html#post-hoc-analyse-meervoudig-vergelijken-van-gemiddelden"><i class="fa fa-check"></i><b>7.3</b> Post hoc analyse: Meervoudig Vergelijken van Gemiddelden</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="chap-anova.html"><a href="chap-anova.html#naïeve-methode"><i class="fa fa-check"></i><b>7.3.1</b> Naïeve methode</a></li>
<li class="chapter" data-level="7.3.2" data-path="chap-anova.html"><a href="chap-anova.html#family-wise-error-rate"><i class="fa fa-check"></i><b>7.3.2</b> Family-wise error rate</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="chap-anova.html"><a href="chap-anova.html#conclusies-prostacycline-voorbeeld"><i class="fa fa-check"></i><b>7.4</b> Conclusies: Prostacycline Voorbeeld</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="niet-parametrische-statistiek.html"><a href="niet-parametrische-statistiek.html"><i class="fa fa-check"></i><b>8</b> Niet-parametrische statistiek</a>
<ul>
<li class="chapter" data-level="8.1" data-path="niet-parametrische-statistiek.html"><a href="niet-parametrische-statistiek.html#inleiding-7"><i class="fa fa-check"></i><b>8.1</b> Inleiding</a></li>
<li class="chapter" data-level="8.2" data-path="niet-parametrische-statistiek.html"><a href="niet-parametrische-statistiek.html#vergelijken-van-twee-groepen"><i class="fa fa-check"></i><b>8.2</b> Vergelijken van twee groepen</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="niet-parametrische-statistiek.html"><a href="niet-parametrische-statistiek.html#cholestorol-voorbeeld"><i class="fa fa-check"></i><b>8.2.1</b> Cholestorol voorbeeld</a></li>
<li class="chapter" data-level="8.2.2" data-path="niet-parametrische-statistiek.html"><a href="niet-parametrische-statistiek.html#permutatietesten"><i class="fa fa-check"></i><b>8.2.2</b> Permutatietesten</a></li>
<li class="chapter" data-level="8.2.3" data-path="niet-parametrische-statistiek.html"><a href="niet-parametrische-statistiek.html#rank-testen"><i class="fa fa-check"></i><b>8.2.3</b> Rank Testen</a></li>
<li class="chapter" data-level="8.2.4" data-path="niet-parametrische-statistiek.html"><a href="niet-parametrische-statistiek.html#wilcoxon-mann-whitney-test"><i class="fa fa-check"></i><b>8.2.4</b> Wilcoxon-Mann-Whitney Test</a></li>
<li class="chapter" data-level="8.2.5" data-path="niet-parametrische-statistiek.html"><a href="niet-parametrische-statistiek.html#conclusie-cholestorol-voorbeeld"><i class="fa fa-check"></i><b>8.2.5</b> Conclusie Cholestorol Voorbeeld</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="niet-parametrische-statistiek.html"><a href="niet-parametrische-statistiek.html#vergelijken-van-g-behandelingen"><i class="fa fa-check"></i><b>8.3</b> Vergelijken van <span class="math inline">\(g\)</span> Behandelingen</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="niet-parametrische-statistiek.html"><a href="niet-parametrische-statistiek.html#dmh-voorbeeld"><i class="fa fa-check"></i><b>8.3.1</b> DMH Voorbeeld</a></li>
<li class="chapter" data-level="8.3.2" data-path="niet-parametrische-statistiek.html"><a href="niet-parametrische-statistiek.html#kruskal-wallis-rank-test"><i class="fa fa-check"></i><b>8.3.2</b> Kruskal-Wallis Rank Test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="chap-categorisch.html"><a href="chap-categorisch.html"><i class="fa fa-check"></i><b>9</b> Categorische data analyse</a>
<ul>
<li class="chapter" data-level="9.1" data-path="chap-categorisch.html"><a href="chap-categorisch.html#inleiding-8"><i class="fa fa-check"></i><b>9.1</b> Inleiding</a></li>
<li class="chapter" data-level="9.2" data-path="chap-categorisch.html"><a href="chap-categorisch.html#toetsen-voor-een-proportie"><i class="fa fa-check"></i><b>9.2</b> Toetsen voor een proportie</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="chap-categorisch.html"><a href="chap-categorisch.html#asymptotisch-betrouwbaarheidsinterval"><i class="fa fa-check"></i><b>9.2.1</b> Asymptotisch Betrouwbaarheidsinterval</a></li>
<li class="chapter" data-level="9.2.2" data-path="chap-categorisch.html"><a href="chap-categorisch.html#asymptotische-test"><i class="fa fa-check"></i><b>9.2.2</b> Asymptotische Test</a></li>
<li class="chapter" data-level="9.2.3" data-path="chap-categorisch.html"><a href="chap-categorisch.html#subsec:binom"><i class="fa fa-check"></i><b>9.2.3</b> Binomiale test</a></li>
<li class="chapter" data-level="9.2.4" data-path="chap-categorisch.html"><a href="chap-categorisch.html#conclusie"><i class="fa fa-check"></i><b>9.2.4</b> Conclusie</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="chap-categorisch.html"><a href="chap-categorisch.html#toets-voor-associatie-tussen-2-kwalitatieve-variabelen"><i class="fa fa-check"></i><b>9.3</b> Toets voor associatie tussen 2 kwalitatieve variabelen</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="chap-categorisch.html"><a href="chap-categorisch.html#gepaarde-gegevens"><i class="fa fa-check"></i><b>9.3.1</b> Gepaarde gegevens</a></li>
<li class="chapter" data-level="9.3.2" data-path="chap-categorisch.html"><a href="chap-categorisch.html#subsec:catOnPaired"><i class="fa fa-check"></i><b>9.3.2</b> Ongepaarde gegevens</a></li>
<li class="chapter" data-level="9.3.3" data-path="chap-categorisch.html"><a href="chap-categorisch.html#de-pearson-chi-kwadraat-test-voor-ongepaarde-gegevens"><i class="fa fa-check"></i><b>9.3.3</b> De Pearson Chi-kwadraat test voor ongepaarde gegevens</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="chap-categorisch.html"><a href="chap-categorisch.html#logistische-regressie"><i class="fa fa-check"></i><b>9.4</b> Logistische regressie</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="chap-categorisch.html"><a href="chap-categorisch.html#categorische-predictor"><i class="fa fa-check"></i><b>9.4.1</b> Categorische predictor</a></li>
<li class="chapter" data-level="9.4.2" data-path="chap-categorisch.html"><a href="chap-categorisch.html#continue-predictor"><i class="fa fa-check"></i><b>9.4.2</b> Continue predictor</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="chap-glm.html"><a href="chap-glm.html"><i class="fa fa-check"></i><b>10</b> Algemeen lineair model</a>
<ul>
<li class="chapter" data-level="10.1" data-path="chap-glm.html"><a href="chap-glm.html#inleiding-9"><i class="fa fa-check"></i><b>10.1</b> Inleiding</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="chap-glm.html"><a href="chap-glm.html#sec:prostate"><i class="fa fa-check"></i><b>10.1.1</b> Prostaatkanker dataset</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="chap-glm.html"><a href="chap-glm.html#het-additieve-meervoudig-lineaire-regressie-model"><i class="fa fa-check"></i><b>10.2</b> Het additieve meervoudig lineaire regressie model</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="chap-glm.html"><a href="chap-glm.html#statistisch-model"><i class="fa fa-check"></i><b>10.2.1</b> Statistisch model</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="chap-glm.html"><a href="chap-glm.html#besluitvorming-in-regressiemodellen"><i class="fa fa-check"></i><b>10.3</b> Besluitvorming in regressiemodellen</a></li>
<li class="chapter" data-level="10.4" data-path="chap-glm.html"><a href="chap-glm.html#nagaan-van-modelveronderstellingen-1"><i class="fa fa-check"></i><b>10.4</b> Nagaan van modelveronderstellingen</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="chap-glm.html"><a href="chap-glm.html#lineariteit-1"><i class="fa fa-check"></i><b>10.4.1</b> Lineariteit</a></li>
<li class="chapter" data-level="10.4.2" data-path="chap-glm.html"><a href="chap-glm.html#homoscedasticiteit"><i class="fa fa-check"></i><b>10.4.2</b> Homoscedasticiteit</a></li>
<li class="chapter" data-level="10.4.3" data-path="chap-glm.html"><a href="chap-glm.html#normaliteit"><i class="fa fa-check"></i><b>10.4.3</b> Normaliteit</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="chap-glm.html"><a href="chap-glm.html#het-niet-additieve-meervoudig-lineair-regressiemodel"><i class="fa fa-check"></i><b>10.5</b> Het niet-additieve meervoudig lineair regressiemodel</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="chap-glm.html"><a href="chap-glm.html#interactie-tussen-continue-variabele-en-factor-variabele"><i class="fa fa-check"></i><b>10.5.1</b> Interactie tussen continue variabele en factor variabele</a></li>
<li class="chapter" data-level="10.5.2" data-path="chap-glm.html"><a href="chap-glm.html#sec:intCont"><i class="fa fa-check"></i><b>10.5.2</b> Interactie tussen twee continue variabelen</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="chap-glm.html"><a href="chap-glm.html#anova-tabel-2"><i class="fa fa-check"></i><b>10.6</b> ANOVA Tabel</a>
<ul>
<li class="chapter" data-level="10.6.1" data-path="chap-glm.html"><a href="chap-glm.html#sstot-ssr-en-sse"><i class="fa fa-check"></i><b>10.6.1</b> SSTot, SSR en SSE</a></li>
<li class="chapter" data-level="10.6.2" data-path="chap-glm.html"><a href="chap-glm.html#extra-kwadratensommen"><i class="fa fa-check"></i><b>10.6.2</b> Extra Kwadratensommen</a></li>
<li class="chapter" data-level="10.6.3" data-path="chap-glm.html"><a href="chap-glm.html#type-i-kwadratensommen"><i class="fa fa-check"></i><b>10.6.3</b> Type I Kwadratensommen</a></li>
<li class="chapter" data-level="10.6.4" data-path="chap-glm.html"><a href="chap-glm.html#type-iii-kwadratensommen"><i class="fa fa-check"></i><b>10.6.4</b> Type III Kwadratensommen</a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="chap-glm.html"><a href="chap-glm.html#regressiediagnostieken"><i class="fa fa-check"></i><b>10.7</b> Regressiediagnostieken</a>
<ul>
<li class="chapter" data-level="10.7.1" data-path="chap-glm.html"><a href="chap-glm.html#multicollineariteit"><i class="fa fa-check"></i><b>10.7.1</b> Multicollineariteit</a></li>
<li class="chapter" data-level="10.7.2" data-path="chap-glm.html"><a href="chap-glm.html#invloedrijke-observaties"><i class="fa fa-check"></i><b>10.7.2</b> Invloedrijke observaties</a></li>
<li class="chapter" data-level="10.7.3" data-path="chap-glm.html"><a href="chap-glm.html#cooks-distance"><i class="fa fa-check"></i><b>10.7.3</b> Cook’s distance</a></li>
</ul></li>
<li class="chapter" data-level="10.8" data-path="chap-glm.html"><a href="chap-glm.html#constrasten"><i class="fa fa-check"></i><b>10.8</b> Constrasten</a>
<ul>
<li class="chapter" data-level="10.8.1" data-path="chap-glm.html"><a href="chap-glm.html#nhanes-voorbeeld-1"><i class="fa fa-check"></i><b>10.8.1</b> NHANES voorbeeld</a></li>
<li class="chapter" data-level="10.8.2" data-path="chap-glm.html"><a href="chap-glm.html#model-3"><i class="fa fa-check"></i><b>10.8.2</b> Model</a></li>
<li class="chapter" data-level="10.8.3" data-path="chap-glm.html"><a href="chap-glm.html#besluitvorming"><i class="fa fa-check"></i><b>10.8.3</b> Besluitvorming</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>11</b> References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Cursus Statistiek 2020-2021</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chap:describe" class="section level1" number="4">
<h1><span class="header-section-number">Hoofdstuk 4</span> Data exploratie en beschrijvende statistiek</h1>
<p>Alle kennisclips die in dit hoofdstuk zijn verwerkt kan je in deze youtube playlist vinden: <a href="https://www.youtube.com/watch?v=AVd-8WE_DhU&amp;list=PLZH1hP8_LbJLKTeg_D9CHC3xbk0nfBa-1">Kennisclips Hoofdstuk4</a></p>
<p>Link naar webpage/script die wordt gebruik in de kennisclips: <a href="https://statomics.github.io/sbc20/rmd/04-dataExploration.html">script Hoofdstuk4</a></p>
<div id="inleiding-3" class="section level2" number="4.1">
<h2><span class="header-section-number">4.1</span> Inleiding</h2>
<iframe width="560" height="315" src="https://www.youtube.com/embed/AVd-8WE_DhU" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen>
</iframe>
<p>Om de resultaten van een experimentele of observationele studie te
rapporteren, is het uiteraard niet mogelijk om per subject waarvoor gegegevens verzameld werden in de studie de bekomen gegevens neer te schrijven. Met
de veelheid aanwezige informatie is het integendeel belangrijk de gegevens
gericht samen te vatten en voor te stellen. Zelfs wanneer het duidelijk is welke analyse er moet uitgevoerd worden, moet er eerst een
basisbeschrijving komen van de verzamelde gegevens. Dit zal mee helpen
aangeven of er geen fouten zijn gemaakt tijdens het onderzoek of bij de
registratie van gegevens. Eventuele anomalieën of zelfs fraude worden in
deze fase opgespoord en tenslotte krijgt men een indruk of voldaan is aan de
onderstellingen (bvb. de onderstelling dat de gegevens Normaal verdeeld zijn<a href="#fn16" class="footnote-ref" id="fnref16"><sup>16</sup></a>) die aan de grond liggen van de voorgestelde
statistische analyses in de latere fase.</p>
<p>De eerste vraag die moet gesteld worden bij het benaderen van een echte data
set is:</p>
<ol style="list-style-type: decimal">
<li>Wat is de oorspronkelijke vraagstelling (geweest), waarom zijn deze
gegevens verzameld?</li>
<li>Hoe en onder welke omstandigheden zijn de subjecten gekozen en de variabelen gemeten? Hierbij stelt men meteen de vraag naar het design van de studie, alsook hoeveel subjecten werden aangezocht voor meetwaarden en hoeveel daar uiteindelijk echt van in de database zijn terecht gekomen (m.a.w. of gegevens die men gepland had te verzamelen, om een of andere reden toch niet bekomen werden). Bovendien laat dit toe om te evalueren of verschillende subjecten in de studie al dan niet meer verwant zijn dan andere subjecten en of de analyse hier rekening mee moet houden.</li>
<li>Is er een specifieke numerieke code die een ontbrekend gegeven of
ander type uitzondering voorstelt in plaats van een echte meetwaarde?</li>
</ol>
<p>Als het vertrekpunt duidelijk is en alle variabelen goed beschreven zijn,
kan men starten met een betekenisvolle exploratie van de gerealiseerde
observaties.</p>
<div class="figure" style="text-align: center"><span id="fig:pop2Samp2PopDataExpl"></span>
<img src="Statistiek_2020_2021_files/figure-html/pop2Samp2PopDataExpl-1.png" alt="Verschillende stappen in een studie. In dit hoofdstuk ligt de focus op de data-exploratie en beschrijvende statistiek" width="100%" />
<p class="caption">
Figuur 4.1: Verschillende stappen in een studie. In dit hoofdstuk ligt de focus op de data-exploratie en beschrijvende statistiek
</p>
</div>
<p>Dit hoofdstuk zullen werken rond een centrale dataset: de NHANES studie.</p>

<div class="example">
<span id="exm:nhanesEx" class="example"><strong>Voorbeeld 4.1  (NHANES studie)  </strong></span>
</div>
<p>De National Health and Nutrition Examination Survey
(NHANES) wordt sinds 1960 op regelmatige basis of genomen. In dit voorbeeld maken we gebruik van de gegevens die werden verzameld tussen 2009-2012 bij 10000 Amerikanen en die werden opgenomen in het R-pakket NHANES. Er werd een groot aantal fysische, demografische, nutritionele, levelsstijl en gezondheidskarakteristieken gecollecteerd in deze studie (zie Tabel <a href="chap-describe.html#tab:nhanesDatExpl">4.1</a>). Merk op dat ontbrekende waarnemingen hier gecodeerd worden a.d.h.b. de code <code>NA</code> (Not Available / Missing Value)</p>
<p><strong>Einde voorbeeld</strong></p>
<table>
<caption>
<span id="tab:nhanesDatExpl">Tabel 4.1: </span>Overzicht van een aantal variabelen uit de NHANES studie.
</caption>
<thead>
<tr>
<th style="text-align:right;">
ID
</th>
<th style="text-align:left;">
Gender
</th>
<th style="text-align:right;">
Age
</th>
<th style="text-align:left;">
Race1
</th>
<th style="text-align:right;">
Weight
</th>
<th style="text-align:right;">
Height
</th>
<th style="text-align:right;">
BMI
</th>
<th style="text-align:right;">
BPSysAve
</th>
<th style="text-align:right;">
TotChol
</th>
<th style="text-align:left;">
SmokeNow
</th>
<th style="text-align:left;">
Smoke100
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
51624
</td>
<td style="text-align:left;">
male
</td>
<td style="text-align:right;">
34
</td>
<td style="text-align:left;">
White
</td>
<td style="text-align:right;">
87.4
</td>
<td style="text-align:right;">
164.7
</td>
<td style="text-align:right;">
32.22
</td>
<td style="text-align:right;">
113
</td>
<td style="text-align:right;">
3.49
</td>
<td style="text-align:left;">
No
</td>
<td style="text-align:left;">
Yes
</td>
</tr>
<tr>
<td style="text-align:right;">
51625
</td>
<td style="text-align:left;">
male
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
Other
</td>
<td style="text-align:right;">
17.0
</td>
<td style="text-align:right;">
105.4
</td>
<td style="text-align:right;">
15.30
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
</tr>
<tr>
<td style="text-align:right;">
51630
</td>
<td style="text-align:left;">
female
</td>
<td style="text-align:right;">
49
</td>
<td style="text-align:left;">
White
</td>
<td style="text-align:right;">
86.7
</td>
<td style="text-align:right;">
168.4
</td>
<td style="text-align:right;">
30.57
</td>
<td style="text-align:right;">
112
</td>
<td style="text-align:right;">
6.70
</td>
<td style="text-align:left;">
Yes
</td>
<td style="text-align:left;">
Yes
</td>
</tr>
<tr>
<td style="text-align:right;">
51638
</td>
<td style="text-align:left;">
male
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:left;">
White
</td>
<td style="text-align:right;">
29.8
</td>
<td style="text-align:right;">
133.1
</td>
<td style="text-align:right;">
16.82
</td>
<td style="text-align:right;">
86
</td>
<td style="text-align:right;">
4.86
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
</tr>
<tr>
<td style="text-align:right;">
51646
</td>
<td style="text-align:left;">
male
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:left;">
White
</td>
<td style="text-align:right;">
35.2
</td>
<td style="text-align:right;">
130.6
</td>
<td style="text-align:right;">
20.64
</td>
<td style="text-align:right;">
107
</td>
<td style="text-align:right;">
4.09
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
</tr>
<tr>
<td style="text-align:right;">
51647
</td>
<td style="text-align:left;">
female
</td>
<td style="text-align:right;">
45
</td>
<td style="text-align:left;">
White
</td>
<td style="text-align:right;">
75.7
</td>
<td style="text-align:right;">
166.7
</td>
<td style="text-align:right;">
27.24
</td>
<td style="text-align:right;">
118
</td>
<td style="text-align:right;">
5.82
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
No
</td>
</tr>
</tbody>
</table>
</div>
<div id="sec:univar" class="section level2" number="4.2">
<h2><span class="header-section-number">4.2</span> Univariate beschrijving van de variabelen</h2>
<iframe width="560" height="315" src="https://www.youtube.com/embed/q-mcuUbNHCg" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen>
</iframe>
<p>In de regel begint men met een <em>univariate</em> inspectie: elke variabele
wordt apart onderzocht. Het is absoluut aan te raden om hierbij eerst alle
ruwe gegevens te bekijken door middel van grafieken (zie verder) alvorens
naar samenvattingsmaten (zoals het gemiddelde) over te stappen. Dit laat toe
om een idee te krijgen hoe de geobserveerde waarden van een veranderlijke
verdeeld zijn in de studiegroep (bvb. welke verdeling de bloeddrukmetingen in de studie hebben)
en of er eventuele <em>uitschieters</em> (d.i. extreme
metingen of <em>outliers</em>) zijn. Met outliers worden observaties
aangegeven die ten opzichte van de geobserveerde verdeling van de waarden in
de data set, extreem zijn, buitenbeentjes.</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="chap-describe.html#cb141-1" aria-hidden="true"></a><span class="co">#De data van de NHANES studie bevindt zich</span></span>
<span id="cb141-2"><a href="chap-describe.html#cb141-2" aria-hidden="true"></a><span class="co">#in het R package NHANES</span></span>
<span id="cb141-3"><a href="chap-describe.html#cb141-3" aria-hidden="true"></a><span class="kw">library</span>(NHANES) <span class="co">#laad NHANES package</span></span>
<span id="cb141-4"><a href="chap-describe.html#cb141-4" aria-hidden="true"></a></span>
<span id="cb141-5"><a href="chap-describe.html#cb141-5" aria-hidden="true"></a><span class="co">#NHANES is een data frame met de gegevens</span></span>
<span id="cb141-6"><a href="chap-describe.html#cb141-6" aria-hidden="true"></a><span class="co">#De rijen bevatten informatie over elk subject</span></span>
<span id="cb141-7"><a href="chap-describe.html#cb141-7" aria-hidden="true"></a><span class="co">#De kolommen de variabelen die werden geregistreerd</span></span>
<span id="cb141-8"><a href="chap-describe.html#cb141-8" aria-hidden="true"></a><span class="co">#vb variabele Gender, BMI, ...</span></span>
<span id="cb141-9"><a href="chap-describe.html#cb141-9" aria-hidden="true"></a><span class="co">#Een variabele (kolom) kan uit de dataframe</span></span>
<span id="cb141-10"><a href="chap-describe.html#cb141-10" aria-hidden="true"></a><span class="co">#worden gehaald door gebruik van het $ teken</span></span>
<span id="cb141-11"><a href="chap-describe.html#cb141-11" aria-hidden="true"></a><span class="co">#en de naam van de variabele</span></span>
<span id="cb141-12"><a href="chap-describe.html#cb141-12" aria-hidden="true"></a><span class="co"># We slaan de frequentietabel voor variable Gender</span></span>
<span id="cb141-13"><a href="chap-describe.html#cb141-13" aria-hidden="true"></a><span class="co"># op in object &#39;tab&#39;</span></span>
<span id="cb141-14"><a href="chap-describe.html#cb141-14" aria-hidden="true"></a></span>
<span id="cb141-15"><a href="chap-describe.html#cb141-15" aria-hidden="true"></a>tab &lt;-<span class="st"> </span><span class="kw">table</span>(NHANES<span class="op">$</span>Gender)</span>
<span id="cb141-16"><a href="chap-describe.html#cb141-16" aria-hidden="true"></a>tab</span></code></pre></div>
<pre><code>## 
## female   male 
##   5020   4980</code></pre>
<p>We maken nu een barplot voor de variabele gender</p>
<ol style="list-style-type: decimal">
<li>We pipen de NHANES data naar ggplot</li>
<li>Als aestetics definiëren we x=Gender</li>
<li>We voegen een laag met een barplot toe via de functie <code>geom_bar</code>. We definiëren de kleur via het argument <code>fill</code></li>
</ol>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="chap-describe.html#cb143-1" aria-hidden="true"></a>NHANES <span class="op">%&gt;%</span></span>
<span id="cb143-2"><a href="chap-describe.html#cb143-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>Gender)) <span class="op">+</span></span>
<span id="cb143-3"><a href="chap-describe.html#cb143-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_bar</span>(<span class="dt">fill=</span><span class="st">&quot;steelblue&quot;</span>)</span></code></pre></div>
<p><img src="Statistiek_2020_2021_files/figure-html/unnamed-chunk-88-1.png" width="672" />
Er zijn weinig methoden voorhanden om <em>nominale</em> variabelen te
beschrijven. In Voorbeeld <a href="chap-describe.html#exm:nhanesEx">4.1</a> is de variable <em>Gender</em>
kwalitatief nominaal.
Alles is gezegd over de verdeling van het geslacht als we weergeven hoeveel vrouwen en mannen zijn opgenomen in de studie.</p>
<p>We stellen vast dat 5020 van de 10000 subjecten, ofwel 50.2% vrouwen in de studie zijn opgenomen.</p>
<p>Een staafdiagram geeft op de X-as de mogelijke uitkomsten van de variabele
aan (bvb. geslacht). Daarbovenop komt een staaf met hoogte evenredig aan
het totaal aantal keer dat die waarde voorkomt in de dataset. De staven staan los van elkaar met een breedte die constant is, maar verder willekeurig. Als de steekproef
representatief is voor de populatie, dan
krijgen we hier misschien een eerste impressie dat er iets meer vrouwen zijn in de populatie.</p>
<p>Voor <em>numerieke continue variabelen</em> wordt het moeilijk om de
frequentie van alle uitkomstwaarden in een tabel te klasseren omdat veel
waarden hoogstens 1 keer voorkomen. Het <em>tak-en-blad diagram</em> (in het
Engels: <em>stem and leaf plot</em> is een middel om toch nog alle
uitkomsten weer te geven. Een voorbeeld is weergegeven in onderstaande R-output voor het BMI in de NHANES studie.</p>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="chap-describe.html#cb144-1" aria-hidden="true"></a><span class="kw">stem</span>(NHANES<span class="op">$</span>BMI)</span></code></pre></div>
<pre><code>## 
##   The decimal point is 1 digit(s) to the right of the |
## 
##   1 | 33333333333333333344444444444444444444444444444444444444444444444444+37
##   1 | 55555555555555555555555555555555555555555555555555555555555555555555+1389
##   2 | 00000000000000000000000000000000000000000000000000000000000000000000+2264
##   2 | 55555555555555555555555555555555555555555555555555555555555555555555+2610
##   3 | 00000000000000000000000000000000000000000000000000000000000000000000+1693
##   3 | 55555555555555555555555555555555555555555555555555555555555555555555+635
##   4 | 00000000000000000000000000000000000000000000000000000000000000000000+255
##   4 | 55555555555555555555555556666666666666666666666666666666666777777777+46
##   5 | 0000011111122222233333444444444444
##   5 | 5556677777789999
##   6 | 133444
##   6 | 567899
##   7 | 
##   7 | 
##   8 | 111</code></pre>
<p>Hier wordt van alle uitkomsten het eerste cijfer of de eerste paar cijfers
op een verticale lijn in volgorde uitgezet in de vorm van een boomstam.
Daaraan worden horizontaal de bladeren gehecht, met name de laatste cijfers
van de geobserveerde uitkomsten. De output geeft bijvoorbeeld aan dat er 3 personen zijn waarvan het afgeronde BMI 55 bedraagt, 2 personen met een afgerond BMI van 56, ….
Gezien de studie zo groot is, is het tak-en-blad diagram niet erg praktisch voor dit voorbeeld.</p>
<p>In een tak-en-blad diagram krijgt men alle individuele uitkomsten nagenoeg
exact te zien, terwijl de vorm die het diagram aanneemt reeds een idee van
de verdeling geeft zoals in een histogram (zie verder). Een vuistregel om de
vorm van de verdeling het best te zien is het aantal takken ongeveer gelijk
te maken aan <span class="math inline">\(1 + \sqrt{n}\)</span>, waarbij <span class="math inline">\(n\)</span> het aantal observaties voorstelt.
Dit aantal kan uiteraard aangepast worden aan de omstandigheden.
Een populair alternatief voor het tak en blad diagram is de <em>eenvoudige frequentietabel</em>. Deze kan men bekomen door de continue variabele (bvb. BMI) om te zetten in een kwalitatieve ordinale variabele, waarvoor vervolgens een frequentietabel wordt weergegeven.</p>
<p>Het grafisch equivalent van dergelijke frequentietabel noemt een <em>histogram</em>, hetgeen men in <code>ggplot</code> bekomt via</p>
<ol style="list-style-type: decimal">
<li>Pipe de data van de NHANES study naar de <code>ggplot</code> functie</li>
<li>Selecteer de variable BMI als de data om in de x-coordinaat te visualiseren voor het aestetics argument van ggplot gebruik hiervoor de <code>aes</code> functie</li>
<li>Voeg een laag toe voor het histogram. Wanneer je geen aestetics <code>aes</code> meegeeft verkrijg je standaard absolute frequenties. Met <code>fill=..counts..</code> in de aestetics kan je de balken van het histogram inkleuren a.d.h.v. de absolute frequenties.</li>
<li>Indien je het wenst kan je op een histogram met densities ook nog een laag toevoegen met een niet parametrische densiteitsschatter voor de verdeling d.m.v. de <code>geom_density</code> functie.</li>
</ol>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="chap-describe.html#cb146-1" aria-hidden="true"></a>NHANES <span class="op">%&gt;%</span></span>
<span id="cb146-2"><a href="chap-describe.html#cb146-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>BMI)) <span class="op">+</span></span>
<span id="cb146-3"><a href="chap-describe.html#cb146-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(<span class="dt">y=</span>..density.., <span class="dt">fill=</span>..count..),<span class="dt">bins=</span><span class="dv">30</span>) <span class="op">+</span></span>
<span id="cb146-4"><a href="chap-describe.html#cb146-4" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_density</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:histo"></span>
<img src="Statistiek_2020_2021_files/figure-html/histo-1.png" alt="Histogram van het BMI in de NHANES studie." width="100%" />
<p class="caption">
Figuur 4.2: Histogram van het BMI in de NHANES studie.
</p>
</div>
<p>Wanneer alle klassen
een zelfde breedte hebben, worden de absolute of relatieve frequenties per
klasse weergegeven door de hoogte van de bijhorende kolom. Bij ongelijke
klassebreedtes is het de oppervlakte van de kolom die met de bijhorende
klassefrequentie correspondeert. Omdat een histogram met ongelijke
klassebreedtes moeilijker te interpreteren is, zijn histogrammen met gelijke
klassebreedtes vaak te verkiezen. Als histogrammen voor verschillende
groepen bekeken worden, vergemakkelijkt het gebruik van <em>relatieve</em>
frequenties i.p.v. absolute frequenties de visuele vergelijkbaarheid.</p>
<p>Op het histogram in Figuur <a href="chap-describe.html#fig:histo">4.2</a> worden densiteiten
weergegeven en klassen met een breedte iets meer dan 5 eenheden.</p>
<p>De keuze van het aantal klassen is van belang bij een histogram. Als er te
weinig klassen zijn, dan gaat veel informatie verloren. Als er teveel zijn,
dan wordt het algemene patroon verdoezeld door een grote hoeveelheid overbodige
details. Gewoonlijk kiest men tussen 5 en 15 intervallen, maar de specifieke
keuze hangt af van het beeld van het histogram dat men te zien krijgt.</p>
<p>Een histogram is vooral geschikt om de distributie te schatten in grote datasets. Daar kan men dan veel intervallen gebruiken. Daarom heeft de ggplot functie standaard 30 intervallen.</p>
<p>Indien een voldoende aantal gegevens beschikbaar is, dan kan men een
gladdere indruk van de verdeling van de gegevens bekomen door een zogenaamde <em>kernel density schatter</em> te bepalen. Zo’n schatter is een positieve functie die genormaliseerd is in die zin dat de oppervlakte onder de functie 1 is. Ze kan zo geïnterpreteerd worden dat de oppervlakte onder de functie tussen 2 punten <span class="math inline">\(a\)</span> en <span class="math inline">\(b\)</span> op de X-as, de kans voorstelt dat een lukrake meting in het interval <span class="math inline">\([a,b]\)</span> gevonden wordt. Figuur <a href="chap-describe.html#fig:histo">4.2</a> toont een histogram met kernel density schatter van de het BMI.</p>
<p>De verdeling kan ook geëvalueerd worden aan de hand van een <em>box-and-whisker-plot</em>, kortweg <em>boxplot</em> genoemd. Deze is
meer compact dan een histogram en laat om die reden gemakkelijker
vergelijkingen tussen verschillende groepen toe (zie verder). Een Boxplot voor het BMI wordt getoond in Figuur <a href="chap-describe.html#fig:boxBMI">4.3</a>. De boxplot toont een
doos lopend van het 25% tot 75% percentiel met een lijntje ter hoogte van de
mediaan (het 50% percentiel) en verder 2 snorharen. Die laatste kunnen in principe lopen tot het
minimum en maximum, of tot het 2.5% en 97.5 % of 5% en 95% percentiel.
R kiest voor de kleinste en de grootste geobserveerde waarde die geen
outlier of extreme waarde zijn. Een meting wordt hierbij een outlier genoemd
wanneer ze meer dan 1.5 keer de boxlengte beneden het eerste of boven het
derde kwartiel ligt. Een meting wordt een extreme waarde genoemd wanneer ze
meer dan 3 keer de boxlengte beneden het eerste of boven het derde kwartiel
ligt.</p>

<div class="definition">
<span id="def:unnamed-chunk-90" class="definition"><strong>Definitie 4.1  (percentiel)  </strong></span>
</div>
<p>Het <em>25% percentiel</em> of <em>25% kwantiel</em> <span class="math inline">\(x_{25}\)</span> van een
reeks waarnemingen wordt gedefinieerd als een uitkomstwaarde <span class="math inline">\(x_{25}\)</span> zodat
minstens <span class="math inline">\(25\%\)</span> van die waarnemingen kleiner of gelijk zijn aan <span class="math inline">\(x_{25}\)</span> en
minstens <span class="math inline">\(75\%\)</span> van die waarnemingen groter of gelijk zijn aan <span class="math inline">\(x_{25}\)</span>. Het
<em>75% percentiel</em> of <em>75% kwantiel</em> van een reeks
waarnemingen definieert men als een uitkomstwaarde <span class="math inline">\(x_{75}\)</span> zodat minstens 75%
kleiner of gelijk zijn aan <span class="math inline">\(x_{75}\)</span> en minstens <span class="math inline">\(25\%\)</span> van die waarnemingen
groter of gelijk zijn aan <span class="math inline">\(x_{75}\)</span>. Algemeen wordt het <em><span class="math inline">\(k\%\)</span>
percentiel</em> van een reeks waarnemingen gedefinieerd als een waarde (van <span class="math inline">\(x\)</span>)
waarvoor de cumulatieve frequentie gelijk is aan <span class="math inline">\(k/100.\)</span> Als er meerdere
observaties aan voldoen neemt men vaak het gemiddelde van die waarden.</p>
<p><strong>Einde definitie</strong></p>
<p>In R kunnen die als volgt worden bekomen</p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="chap-describe.html#cb147-1" aria-hidden="true"></a><span class="kw">quantile</span>(NHANES<span class="op">$</span>BMI,<span class="kw">c</span>(<span class="fl">0.25</span>,.<span class="dv">5</span>,.<span class="dv">75</span>),<span class="dt">na.rm=</span><span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>##   25%   50%   75% 
## 21.58 25.98 30.89</code></pre>
<div class="figure" style="text-align: center"><span id="fig:boxBMI"></span>
<img src="Statistiek_2020_2021_files/figure-html/boxBMI-1.png" alt="Boxplot van BMI in de NHANES studie." width="100%" />
<p class="caption">
Figuur 4.3: Boxplot van BMI in de NHANES studie.
</p>
</div>
<p>In ggplot maak je de boxplot als volgt:</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="chap-describe.html#cb149-1" aria-hidden="true"></a>NHANES <span class="op">%&gt;%</span></span>
<span id="cb149-2"><a href="chap-describe.html#cb149-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span><span class="st">&quot;&quot;</span>,<span class="dt">y=</span>BMI)) <span class="op">+</span></span>
<span id="cb149-3"><a href="chap-describe.html#cb149-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_boxplot</span>()</span></code></pre></div>
<p><img src="Statistiek_2020_2021_files/figure-html/unnamed-chunk-92-1.png" width="672" /></p>
<p>Bij de inspectie van een dataset speelt het detecteren van outliers in het
algemeen een belangrijke rol. Ze kunnen wijzen op fouten, zoals tikfouten of
andere fouten die gecheckt en gecorrigeerd moeten worden. Als het geen
foutief genoteerde waarden zijn, dan kan het soms wijzen op een subject dat niet
echt in de studiepopulatie thuis hoort. Als het in
alle opzichten om een bona fide waarde gaat, dan nog is het belangrijk om
outliers te detecteren: ze kunnen zeer invloedrijk zijn op de schatting van
statistische parameters (zie Sectie <a href="chap-describe.html#sec:summarize">4.3</a>). Als de conclusies
van een studie anders liggen met of zonder inclusie van de outlier, dan is
dit een ongewenst fenomeen. Men wil immers nooit dat 1 observatie beslissend
is voor de conclusies. Dit soort onzekerheid ondermijnt de geloofwaardigheid
van de onderzoeksresultaten en vraagt om verdere studie. Binnen de
statistiek bestaat een grote waaier aan technieken, zogenaamde
<em>robuuste statistische technieken</em>, die erop gericht zijn om de invloed van
outliers te minimaliseren. In deze cursus gaan we hier slechts in zeer
beperkte mate op in (zie Sectie <a href="chap-describe.html#sec:summarize">4.3</a>, mediaan).</p>
</div>
<div id="sec:summarize" class="section level2" number="4.3">
<h2><span class="header-section-number">4.3</span> Samenvattingsmaten voor continue variabelen</h2>
<iframe width="560" height="315" src="https://www.youtube.com/embed/nY3ONJlySUk" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen>
</iframe>
<p>Een histogram levert reeds een sterke samenvatting van de geobserveerde,
continue gegevens, maar in wetenschappelijke rapporten is er zelden
plaats om per geobserveerde variabele dergelijke grafiek voor te stellen. Om
die reden is vaak een veel drastischere samenvattingsmaat noodzakelijk. In deze
sectie geven we aan hoe de centrale locatie van de gegevens kan beschreven
worden, alsook de spreiding van die gegevens rond hun centrale locatie.</p>
<div id="maten-voor-de-centrale-ligging" class="section level3" number="4.3.1">
<h3><span class="header-section-number">4.3.1</span> Maten voor de centrale ligging</h3>

<div class="definition">
<span id="def:unnamed-chunk-93" class="definition"><strong>Definitie 4.2  (rekenkundig gemiddelde)  </strong></span>
</div>
<p>Het <strong>(rekenkundig) gemiddelde</strong> <span class="math inline">\(\overline{x}\)</span> (spreek uit: <em>x-streep</em>
of <em>x-bar</em>) van een reeks waarnemingen <span class="math inline">\(x_i, i=1, 2, \dots, n\)</span> is per
definitie de som van de observaties gedeeld door hun aantal <span class="math inline">\(n\)</span>:</p>
<p><span class="math display">\[\overline{x}= \frac{x_1 + x_2 + \dots + x_n}{n} =\sum_{i=1}^n x_i \frac{1}{n} \]</span></p>
<p><strong>Einde definitie</strong></p>
<p>Merk op dat het rekenkundig gemiddelde ook verkregen zou worden als gemiddelde voor een discrete distributie met kansen van 1/n op elke waarde uit de steekproef.
Wanneer we het steekproefgemiddelde gebruiken dan schatten we de distributie in de populatie als het ware aan de hand van de empirische distributie van de data. We maken dus geen distributionele veronderstellingen hiervoor.</p>
<p>Een groot voordeel van het gemiddelde als een maat voor de centrale locatie
van de observaties is dat het alle data-waarden efficiënt gebruikt vanuit
statistisch perspectief. Dit wil zeggen dat ze (onder bepaalde statistische modellen)
het maximum aan informatie
uit de gegevens haalt en om die reden relatief gezien zeer stabiel blijft
wanneer ze herberekend wordt op basis van een nieuwe, even grote steekproef
die onder identieke omstandigheden werd bekomen. Bovendien beschrijft het
gemiddelde ook verschillende belangrijke modellen voor de verdeling van de
gegevens, zoals de Normale verdeling (zie Sectie <a href="chap-describe.html#sec:normal">4.4</a>). Een
groot nadeel van het gemiddelde is dat het zeer gevoelig is aan de
aanwezigheid van outliers in de dataset. Om die reden is het vooral een
interessante maat van locatie wanneer de verdeling van de observaties (zoals
weergegeven door bijvoorbeeld een histogram) min of meer symmetrisch is.</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="chap-describe.html#cb150-1" aria-hidden="true"></a><span class="kw">mean</span>(NHANES<span class="op">$</span>BMI,<span class="dt">na.rm=</span><span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 26.66014</code></pre>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="chap-describe.html#cb152-1" aria-hidden="true"></a><span class="co">#opnieuw is de na.rm statement hier nodig</span></span>
<span id="cb152-2"><a href="chap-describe.html#cb152-2" aria-hidden="true"></a><span class="co">#omdat ontbrekende waarden voorkomen.</span></span></code></pre></div>
<p><em>Indien men de grootste observatie (81.25) vervangt door 8125 om als het ware ene tikfout voor te stellen, dan wijzigt het rekenkundig gemiddelde naar 27.5 en dat terwijl er bijna 10000 BMI metingen zijn. Merk op dat het gemiddelde vrij sterk beïnvloed kan worden door één outlier.</em></p>
<p><strong>Eigenschap</strong></p>
<p>Als alle uitkomsten <span class="math inline">\(x_i\)</span> met een willekeurige constante <span class="math inline">\(a\)</span>
worden vermenigvuldigd, dan ook het gemiddelde van die reeks uitkomsten. Als
bij alle uitkomsten een constante <span class="math inline">\(a\)</span> wordt opgeteld, dan ook bij het
gemiddelde van die reeks uitkomsten. Formeel betekent dit:</p>
<p><span class="math display">\[\begin{eqnarray*}
\overline{ax} &amp;= &amp;a \overline{x} \\
\overline{a + x} &amp;= &amp;a + \overline{x}
\end{eqnarray*}\]</span></p>
<p>Voor 2 reeksen getallen <span class="math inline">\(x_i\)</span> en <span class="math inline">\(y_i\)</span>, <span class="math inline">\(i=1,...,n\)</span>, geldt dat het
gemiddelde van de som van de observaties gelijk is aan de som van hun
gemiddelden:</p>
<p><span class="math display">\[\begin{equation*}
\overline{x + y} = \overline{x} + \overline{y}.
\end{equation*}\]</span></p>
<p>Als de gegevens <span class="math inline">\(x_i\)</span> enkel de waarden 0 of 1 aannemen, dan is <span class="math inline">\(\overline{x}\)</span>
de proportie subjecten voor wie de waarde 1 werd geobserveerd. Immers, zij <span class="math inline">\(n_1\)</span> het aantal subjecten binnen de groep van <span class="math inline">\(n\)</span> subjecten waarvoor de
waarde 1 werd geobserveerd, dan is</p>
<p><span class="math display">\[\begin{equation*}
\overline{x}= \sum_{i=1}^n \frac{x_i}{n} = \frac{n_1}{n}.
\end{equation*}\]</span></p>
<p>Bijvoorbeeld, als we de variabele <strong>Gender</strong> zó
coderen dat mannen een waarde 0 aannemen en vrouwen een waarde 1, dan is het
gemiddelde van de variabele <strong>Gender</strong> gelijk aan 50.2%, hetgeen de proportie is van het aantal vrouwen in de studie. Een percentage kan dus
steeds opgevat worden als het gemiddelde van een geschikte variabele.</p>
<p><strong>Einde eigenschap</strong></p>
<p>Een centrale maat die robuuster reageert dan het gemiddelde, d.w.z. minder
of niet gevoelig is aan outliers, is de <em>mediaan</em> of het <em>50% percentiel</em>.</p>

<div class="definition">
<span id="def:unnamed-chunk-95" class="definition"><strong>Definitie 4.3  (mediaan)  </strong></span>
</div>
<p>De <strong>mediaan</strong>, het <strong>50% percentiel</strong> of het <strong>50%
kwantiel</strong> <span class="math inline">\(x_{50}\)</span> van een reeks waarnemingen <span class="math inline">\(x_i, i=1, 2, \dots, n\)</span> is per
definitie een uitkomstwaarde <span class="math inline">\(x_{50}\)</span> zodat minstens <span class="math inline">\(50\%\)</span> van die
waarnemingen groter of gelijk zijn aan <span class="math inline">\(x_{50}\)</span> en minstens <span class="math inline">\(50\%\)</span> van die
waarnemingen kleiner of gelijk zijn aan <span class="math inline">\(x_{50}\)</span>.</p>
<p><strong>Einde definitie</strong></p>
<p>Om de mediaan te schatten, rangschikt men eerst de gegevens volgens grootte.
Als het aantal observaties <span class="math inline">\(n\)</span> oneven is, dan is een schatting voor de
mediaan de middelste waarneming. Indien <span class="math inline">\(n\)</span> even is, dan zijn er 2 middelste
waarnemingen en schat men de mediaan (meestal) als hun gemiddelde. Een
voordeel van de mediaan is dat ze niet gevoelig is aan outliers. In het bijzonder kan
ze vaak nuttig aangewend worden wanneer sommige gegevens <em>gecensureerd</em>
zijn. Dit wil zeggen dat men voor een aantal gegevens enkel weet dat ze
boven of onder een bepaalde drempelwaarde liggen.</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="chap-describe.html#cb153-1" aria-hidden="true"></a><span class="kw">median</span>(NHANES<span class="op">$</span>BMI,<span class="dt">na.rm=</span><span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 25.98</code></pre>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="chap-describe.html#cb155-1" aria-hidden="true"></a><span class="co">#Merk op dat we hier gebruik maken van het argument na.rm=TRUE</span></span>
<span id="cb155-2"><a href="chap-describe.html#cb155-2" aria-hidden="true"></a><span class="co">#Dit komt omdat we niet beschikken over het BMI</span></span>
<span id="cb155-3"><a href="chap-describe.html#cb155-3" aria-hidden="true"></a><span class="co">#voor elke persoon: ontbrekende waarnemingen</span></span>
<span id="cb155-4"><a href="chap-describe.html#cb155-4" aria-hidden="true"></a><span class="co">#Die worden in R als een NA voorgesteld</span></span>
<span id="cb155-5"><a href="chap-describe.html#cb155-5" aria-hidden="true"></a><span class="co">#Als we het argument na.rm=TRUE gebruiken wordt</span></span>
<span id="cb155-6"><a href="chap-describe.html#cb155-6" aria-hidden="true"></a><span class="co">#de mediaan berekend op basis van de beschikbare observaties</span></span></code></pre></div>
<p>Indien men de grootste observatie (81.25) vervangt 8125, dan wijzigt de mediaan niet.
Merk ook op dat de mediaan lager is dan het gemiddelde, hij is minder gevoelig voor de outliers in de dataset.</p>

<div class="definition">
<span id="def:unnamed-chunk-97" class="definition"><strong>Definitie 4.4  (modus)  </strong></span>
</div>
<p>De <strong>modus</strong> van een reeks observaties is de waarde die het meest
frequent is, of wanneer de gegevens gegroepeerd worden, de klasse met de
hoogste frequentie.</p>
<p><strong>Einde definitie</strong></p>
<p>De modus wordt niet vaak gebruikt in statistische analyse omdat haar waarde
sterk afhangt van de nauwkeurigheid waarmee de gegevens werden gemeten. Zo
is de modus van de reeks observaties <span class="math inline">\(1, 1, 1, 1.5, 1.75, 1.9, 2, 2.1, 2.4\)</span>
gelijk aan 1, maar wordt ze 2 wanneer alle observaties afgerond worden tot
gehele getallen. Bovendien is de modus niet eenvoudig te schatten voor
continue data waar de frequentie van elke geobserveerde waarde meestal 1 is.
De modus is daarom het meest zinvol voor kwalitatieve en discrete numerieke
gegevens, waar ze de meest frequente klasse aanduidt.</p>
<p>Als de observaties uit een <em>symmetrische verdeling</em> afkomstig zijn,
vallen de mediaan en het gemiddelde nagenoeg samen (als de geobserveerde
verdeling perfect symmetrisch is, vallen ze theoretisch exact samen).
De beste schatter voor het centrum van de verdeling op basis van de beschikbare
steekproef is dan het gemiddelde eerder dan de mediaan van die observaties.
Inderdaad, als men telkens opnieuw een lukrake steekproef neemt uit de
gegeven studiepopulatie en voor elke steekproef het gemiddelde en de mediaan
berekent, dan zal het gemiddelde minder variëren van steekproef tot
steekproef dan de mediaan. Ze is bijgevolg stabieler en wordt daarom een
<em>meer precieze schatter</em> genoemd. Intuïtief kan men begrijpen dat
het gemiddelde meer informatie uit de gegevens gebruikt: niet alleen of iets
groter of kleiner is dan <span class="math inline">\(x_{50}\)</span> maar ook hoeveel groter of kleiner de
exacte waarde van elke observatie is, wordt in de berekening betrokken.</p>

<div class="definition">
<span id="def:unnamed-chunk-98" class="definition"><strong>Definitie 4.5  (scheve verdeling)  </strong></span>
</div>
<p>Een niet-symmetrische verdeling wordt <strong>scheef</strong> genoemd. Als de
waarden rechts van de mediaan verder uitlopen dan links, dan is de verdeling
<em>scheef naar rechts</em> (in het Engels: <em>positively skew</em>) en is
het gemiddelde (meestal) groter dan de mediaan. Als de waarden links van de
mediaan verder uitlopen dan rechts, dan is de verdeling <em>scheef naar
links</em> (in het Engels: <em>negatively skew</em>) en is het gemiddelde
(meestal) kleiner dan de mediaan.</p>
<p><strong>Einde definitie</strong></p>
<p>Voor een niet-symmetrische verdeling is de mediaan veelal een beter
interpreteerbare maat dan het gemiddelde omdat ze minder beïnvloed is
door de staarten van de verdeling en daarom beter het centrum van de
verdeling aanduidt. Maar in sommige gevallen, zoals bijvoorbeeld voor `de
gemiddelde opbrengst per week’, blijft het gemiddelde zinvol omdat het
meteen verwijst naar de totale opbrengst over alle weken (gelijk aan <span class="math inline">\(n\)</span>
keer het gemiddelde als <span class="math inline">\(n\)</span> weken werden geobserveerd). Ook voor
kwalitatieve variabelen kan een gemiddelde zinvol zijn. Voor binaire
nominale variabelen die als 1 of 0 gecodeerd zijn, geeft het gemiddelde
immers het percentage observaties gelijk aan 1 weer. Voor ordinale
variabelen die bijvoorbeeld gecodeerd zijn als <span class="math inline">\(1, 2, 3, ...\)</span> levert het
gemiddelde soms nuttigere informatie dan de mediaan. Niettemin berust het
dan op de impliciete onderstelling dat een wijziging van score van 1 naar 2
even belangrijk is als een wijziging van 2 naar 3.</p>
<p>Om scheve verdelingen in een paar woorden te beschrijven is het vaak nuttig
om</p>
<ul>
<li>ofwel de gegevens te beschrijven in termen van percentielen,</li>
<li>ofwel de gegevens te transformeren naar een andere schaal (bvb. door
logaritmen te nemen), zodat ze op de nieuwe schaal bij benadering
symmetrisch verdeeld zijn.</li>
</ul>
<p>Wanneer het gemiddelde groter is dan de mediaan en alle metingen positief zijn (vb concentraties, BMI), dan is een logaritmische
transformatie van de gegevens vaak nuttig om de scheefheid weg te nemen. In
dit geval is vooral het <em>geometrisch gemiddelde</em> interessant.</p>
<!---break-->
<iframe width="560" height="315" src="https://www.youtube.com/embed/lkKz_PAXab8" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen>
</iframe>

<div class="definition">
<span id="def:unnamed-chunk-99" class="definition"><strong>Definitie 4.6  (geometrisch gemiddelde)  </strong></span>
</div>
<p>Het <strong>geometrische gemiddelde</strong> van een reeks waarnemingen <span class="math inline">\(x_i, i=1, 2, \dots, n\)</span> ontstaat door er de natuurlijke logaritme van te berekenen, het
gemiddelde hiervan te nemen en dit vervolgens terug te transformeren naar de
originele schaal door er de exponentiële functie van te nemen:</p>
<p><span class="math display">\[\begin{equation*}
\sqrt[n]{\prod\limits_{i=1}^n x_i} = \exp\left\{\frac{1}{n} \sum_{i=1}^n \log(x_i)\right\}
\end{equation*}\]</span></p>
<p><strong>Einde definitie</strong></p>
<ul>
<li><p>Geometrisch gemiddelde ligt dichter bij de mediaan dan het gemiddelde</p></li>
<li><p>log-transformatie verwijdert scheefheid</p></li>
<li><p>Is vaak een meer geschikte maat voor centrale locatie dan de mediaan:</p></li>
</ul>
<ol style="list-style-type: decimal">
<li>Gebruikt alle observatie: is meer precies</li>
<li>Is het rekenkundig gemiddelde van log-transformeerde data <span class="math inline">\(\rightarrow\)</span> klassieke statistische methoden kunnen direct worden gebruikt, b.v. hypothese testen en betrouwbaarheidsintervallen (zie hoofdstuk 5)</li>
<li>Veel biologische en chemische variabelen zoals concentraties, intensiteiten, etc kunnen niet negatief zijn.</li>
<li>Verschillen op log schaal hebben de betekenis van een <code>log fold change</code>:</li>
</ol>
<p><span class="math display">\[
\log (B) - \log(A)= \log(\frac{B}{A})=\log(FC_\text{B vs A})
\]</span></p>
<ul>
<li><p>In Genomics wordt de <span class="math inline">\(\log_2\)</span> transformatie veel gebruikt.</p></li>
<li><p>Een verschil van 1 op <span class="math inline">\(\log_2\)</span> schaal betekent een verdubbeling op de originele schaal <span class="math inline">\(FC=2\)</span>.</p></li>
</ul>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="chap-describe.html#cb156-1" aria-hidden="true"></a>logSummary &lt;-</span>
<span id="cb156-2"><a href="chap-describe.html#cb156-2" aria-hidden="true"></a>NHANES <span class="op">%&gt;%</span></span>
<span id="cb156-3"><a href="chap-describe.html#cb156-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">filter</span>(Gender<span class="op">==</span><span class="st">&quot;female&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb156-4"><a href="chap-describe.html#cb156-4" aria-hidden="true"></a><span class="st">  </span><span class="kw">summarize</span>(</span>
<span id="cb156-5"><a href="chap-describe.html#cb156-5" aria-hidden="true"></a>    <span class="dt">logMean =</span> <span class="kw">mean</span>(BMI <span class="op">%&gt;%</span><span class="st"> </span>log2,<span class="dt">na.rm=</span><span class="ot">TRUE</span>),</span>
<span id="cb156-6"><a href="chap-describe.html#cb156-6" aria-hidden="true"></a>    <span class="dt">sd =</span> <span class="kw">sd</span>(BMI <span class="op">%&gt;%</span><span class="st"> </span>log2,<span class="dt">na.rm=</span><span class="ot">TRUE</span>),</span>
<span id="cb156-7"><a href="chap-describe.html#cb156-7" aria-hidden="true"></a>    <span class="dt">mean =</span> <span class="kw">mean</span>(BMI,<span class="dt">na.rm=</span><span class="ot">TRUE</span>),</span>
<span id="cb156-8"><a href="chap-describe.html#cb156-8" aria-hidden="true"></a>    <span class="dt">median =</span> <span class="kw">median</span>(BMI,<span class="dt">na.rm=</span><span class="ot">TRUE</span>)</span>
<span id="cb156-9"><a href="chap-describe.html#cb156-9" aria-hidden="true"></a>    ) <span class="op">%&gt;%</span></span>
<span id="cb156-10"><a href="chap-describe.html#cb156-10" aria-hidden="true"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">geoMean=</span><span class="dv">2</span><span class="op">^</span>logMean)</span>
<span id="cb156-11"><a href="chap-describe.html#cb156-11" aria-hidden="true"></a></span>
<span id="cb156-12"><a href="chap-describe.html#cb156-12" aria-hidden="true"></a>NHANES <span class="op">%&gt;%</span></span>
<span id="cb156-13"><a href="chap-describe.html#cb156-13" aria-hidden="true"></a><span class="st">  </span><span class="kw">filter</span>(Gender<span class="op">==</span><span class="st">&quot;female&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb156-14"><a href="chap-describe.html#cb156-14" aria-hidden="true"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>BMI <span class="op">%&gt;%</span><span class="st"> </span>log2)) <span class="op">+</span></span>
<span id="cb156-15"><a href="chap-describe.html#cb156-15" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_histogram</span>(</span>
<span id="cb156-16"><a href="chap-describe.html#cb156-16" aria-hidden="true"></a>    <span class="kw">aes</span>(<span class="dt">y=</span>..density.., <span class="dt">fill=</span>..count..),</span>
<span id="cb156-17"><a href="chap-describe.html#cb156-17" aria-hidden="true"></a>    <span class="dt">bins=</span><span class="dv">30</span>) <span class="op">+</span></span>
<span id="cb156-18"><a href="chap-describe.html#cb156-18" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_density</span>() <span class="op">+</span></span>
<span id="cb156-19"><a href="chap-describe.html#cb156-19" aria-hidden="true"></a><span class="st">  </span><span class="kw">stat_function</span>(<span class="dt">fun=</span>dnorm,</span>
<span id="cb156-20"><a href="chap-describe.html#cb156-20" aria-hidden="true"></a>    <span class="dt">color=</span><span class="st">&quot;red&quot;</span>,</span>
<span id="cb156-21"><a href="chap-describe.html#cb156-21" aria-hidden="true"></a>    <span class="dt">args=</span><span class="kw">list</span>(</span>
<span id="cb156-22"><a href="chap-describe.html#cb156-22" aria-hidden="true"></a>      <span class="dt">mean=</span>logSummary<span class="op">$</span>logMean,</span>
<span id="cb156-23"><a href="chap-describe.html#cb156-23" aria-hidden="true"></a>      <span class="dt">sd=</span>logSummary<span class="op">$</span>sd)</span>
<span id="cb156-24"><a href="chap-describe.html#cb156-24" aria-hidden="true"></a>    )</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:histLogBMI"></span>
<img src="Statistiek_2020_2021_files/figure-html/histLogBMI-1.png" alt="Boxplot van BMI en log(BMI) in de NHANES studie." width="100%" />
<p class="caption">
Figuur 4.4: Boxplot van BMI en log(BMI) in de NHANES studie.
</p>
</div>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="chap-describe.html#cb157-1" aria-hidden="true"></a>logSummary</span></code></pre></div>
<pre><code>## # A tibble: 1 x 5
##   logMean    sd  mean median geoMean
##     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
## 1    4.68 0.408  26.8   25.6    25.7</code></pre>
<p>In situaties waar de log-transformatie inderdaad de scheefheid wegneemt, zal
het geometrisch gemiddelde dichter bij de mediaan liggen dan het gemiddelde.
Wanneer de verdeling scheef is, is ze soms zelfs een nuttigere maat voor centrale
locatie dan de mediaan:</p>
<ol style="list-style-type: decimal">
<li><p>omdat ze ook gebruik maakt van de exacte waarden van de observaties en
daarom doorgaans preciezer is dan de mediaan;</p></li>
<li><p>omdat ze, op een transformatie na, berekend wordt als een rekenkundig
gemiddelde (weliswaar van de logaritmisch getransformeerde observaties) en
algemene statistische technieken voor een gemiddelde (zoals
betrouwbaarheidsintervallen (zie volgende hoofdstukken) en toetsen van hypothesen (zie volgende hoofdstukken) daardoor vrijwel rechtstreeks
toepasbaar zijn voor geometrische gemiddelden.</p></li>
</ol>

<div class="example">
<span id="exm:unnamed-chunk-100" class="example"><strong>Voorbeeld 4.2  (BMI)  </strong></span>
</div>
<p>Het gemiddelde en mediane BMI bedraagt 26.66 en 25.98 , respectievelijk. Het gemiddelde is hier groter dan de mediaan omdat de BMI scheef verdeeld is naar rechts (zie Figuur <a href="chap-describe.html#fig:histLogBMI">4.4</a>). De verdeling wordt meer symmetrisch na log-transformatie. Het gemiddelde en mediane log-BMI liggen ook dichter bij elkaar en bedragen respectievelijk 3.25 en 3.26. De geometrisch gemiddelde BMI-concentratie bekomen we door de exponentiële functie te evalueren in 3.25, hetgeen ons 25.69 oplevert. Merk op dat dit inderdaad beter met de mediaan overeenstemt dan het rekenkundig gemiddelde.</p>
<p><strong>Einde voorbeeld</strong></p>
<p>Tot slot, vooraleer een eenvoudige maat voor de centrale ligging (en
spreiding) te construeren of interpreteren, is het goed om altijd eerst de
volledige verdeling te bekijken! Immers, stel dat men het gemiddelde of
mediaan berekent van gegevens uit een bimodale verdeling (d.i. een verdeling
met 2 modi, voor bvb. zieken en niet-zieke dieren). Dan kan het gemiddelde of
mediaan makkelijk een zeer zeldzame waarde aannemen die geenszins in de
buurt van 1 van beide maxima ligt.</p>
<!---break-->
</div>
<div id="subsec:spreiding" class="section level3" number="4.3.2">
<h3><span class="header-section-number">4.3.2</span> Spreidingsmaten</h3>
<iframe width="560" height="315" src="https://www.youtube.com/embed/0v8-4cRiDFg" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen>
</iframe>
<p>Nadat de centrale ligging van de gegevens werd bepaald, is men in tweede
instantie geïnteresseerd in de spreiding van de gegevens rond
die centrale waarde. Er zijn verschillende redenen waarom daar interesse in bestaat:</p>
<ol style="list-style-type: decimal">
<li>Om risico’s te berekenen (zie Sectie <a href="chap-describe.html#sec:normal">4.4</a>) volstaat het niet om de centrale locatie van de gegevens te kennen, maar moet men bovendien weten hoeveel de gegevens rond die waarde variëren. Inderdaad, stel dat men wenst te weten welk percentage van de subjecten een BMI heeft van boven de 35. Wetende dat een geometrisch gemiddelde van 25.69 wordt geobserveerd, zal dat percentage relatief hoog zijn wanneer de metingen zeer gespreid zijn en relatief laag anders.</li>
<li>Veldbiologen zijn vaak geïnteresseerd in de mate waarin dieren of planten verspreid zijn over een zeker studiegebied. Op die manier kunnen ze immers leren over de relaties tussen individuen onderling en met hun omgeving. Daartoe zal men in de praktijk op verschillende plaatsen in het studiegebied tellingen maken van het aantal individuen op die plaats. Men kan aantonen dat, onder bepaalde veronderstellingen, individuen lukraak verspreid zijn over het studiegebied wanneer de spreiding op die tellingen, zoals gemeten door de variantie (zie verder), van dezelfde grootte-orde is als de gemiddelde telling. Indien de spreiding groter is, dan hebben individuen de neiging om zich te groeperen. Andersom, indien de spreiding op die tellingen lager is dan de gemiddelde telling, dan zijn de individuen zeer uniform verdeeld over het studiegebied.</li>
<li>Stel dat men een zekere uitkomst (bvb. het aantal species ongewervelde dieren in een stuk bodemkorst) wenst te vergelijken tussen 2 groepen (bvb. gebieden met en zonder bosbrand), dan zal men een duidelijk beeld van het groepseffect krijgen wanneer de uitkomst weinig gespreid is, maar een veel minder duidelijk beeld wanneer de gegevens meer chaotisch (en dus meer gespreid) zijn. Om uit te maken of een interventie-effect toevallig of systematisch is, moet men daarom een idee hebben van de spreiding op de gegevens.</li>
</ol>
<p>Dat uitkomsten variëren tussen individuen en binnen individuen omwille van
allerlei redenen ligt aan de basis van de statistische analyse van veel
fenomenen. Het goed beschrijven van variatie naast de centrale locatie van
de gegevens is daarom belangrijk! Hierbij zal men typisch een
onderscheid maken tussen variatie die men kan verklaren (door middel van
karakteristieken, zoals bijvoorbeeld de leeftijd, van de bestudeerde individuen) en onverklaarde variatie. We gaan
dieper in op dit onderscheid in Hoofdstuk <a href="chap-linReg.html#chap:linReg">6</a> rond lineaire regressie.</p>
<p>Variatie betekent dat niet alle observaties <span class="math inline">\(x_i\)</span> gelijk zijn aan het
gemiddelde <span class="math inline">\(\overline{x}\)</span>. De afwijking <span class="math inline">\(x_i - \bar{x}\)</span> is om die reden
interessant. Het gemiddelde van die afwijkingen is echter altijd 0
(verifieer!) omdat positieve en negatieve afwijkingen mekaar opheffen.
Bijgevolg levert de gemiddelde afwijking geen goede maat op voor de variatie
en is het beter om bijvoorbeeld naar kwadratische afwijkingen <span class="math inline">\((x_i - \bar{x})^2\)</span> te kijken. Het gemiddelde van die <em>kwadratische afwijkingen rond het gemiddelde</em>, het gemiddelde dus van <span class="math inline">\((x_i - \bar{x})^2\)</span>, levert daarom
wel een goede maat op. Merk op dat we bij het berekenen van het gemiddelde niet delen door het aantal observaties <span class="math inline">\(n\)</span>, maar door <span class="math inline">\(n-1\)</span> waarbij we corrigeren voor het feit dat we voor de berekening van de steekproef variantie 1 vrijheidsgraad hebben gespendeerd aan het schatten van het gemiddelde.</p>

<div class="definition">
<span id="def:unnamed-chunk-101" class="definition"><strong>Definitie 4.7  (variantie)  </strong></span>
</div>
<p>De <strong>variantie</strong> een reeks waarnemingen <span class="math inline">\(x_i, i=1, 2, \dots, n\)</span> is per
definitie</p>
<p><span class="math display">\[\begin{equation*}
s^2_x = \sum_{i=1}^{n} \frac{(x_i - \bar{x})^2}{n-1}
\end{equation*}\]</span></p>
<p>Als duidelijk is om welke waarnemingen het gaat, wordt dit ook met <span class="math inline">\(s^2\)</span>
genoteerd.</p>
<p><strong>Einde definitie</strong></p>
<p>Indien alle observaties gelijk waren en er dus geen variatie was, dan zou
hun variantie 0 bedragen. Hoe meer de gegevens uitgesmeerd zijn rond hun
gemiddelde, hoe groter <span class="math inline">\(s^2\)</span>. Helaas is de waarde van de variantie zelf niet
gemakkelijk te interpreteren. Dit is deels omdat door het kwadrateren de
variantie niet langer de dimensie van de oorspronkelijke waarnemingen heeft.
Handiger om mee te werken is daarom de <em>standaarddeviatie</em> of <em>
standaardafwijking</em>:</p>
<p><span class="math display">\[\begin{equation*}
s_x= \sqrt{s_x^2} .
\end{equation*}\]</span></p>
<p>De standaarddeviatie is gedefinieerd voor elke numerieke variabele, maar is
vooral nuttig omdat voor heel wat variabelen (in het bijzonder Normaal
verdeelde variabelen - zie Sectie <a href="chap-describe.html#sec:normal">4.4</a>) bij benadering 68% van
de waarnemingen liggen tussen <span class="math inline">\(\bar{x} - s_x\)</span> en <span class="math inline">\(\bar{x} + s_x\)</span>, en 95%
van de waarnemingen liggen tussen<a href="#fn17" class="footnote-ref" id="fnref17"><sup>17</sup></a>
<span class="math inline">\(\bar{x} - 2 s_x\)</span> en <span class="math inline">\(\bar{x} + 2 s_x\)</span>. Deze intervallen noemt men respectievelijk 68% en 95% <em>referentie-intervallen</em>. Het is precies deze eigenschap die de
standaarddeviatie zo nuttig maakt in de praktijk. De standaarddeviatie van
een reeks waarnemingen wordt vaak afgekort als SD in de wetenschappelijke literatuur.</p>
<p><strong>Eigenschap</strong></p>
<p>Als alle uitkomsten <span class="math inline">\(x_i\)</span> met een willekeurige constante <span class="math inline">\(a\)</span>
worden vermenigvuldigd, dan wordt hun variantie vermenigvuldigd met <span class="math inline">\(a^2\)</span> en
hun standaarddeviatie met <span class="math inline">\(|a|\)</span> (de absolute waarde van <span class="math inline">\(a\)</span>). Als bij alle
uitkomsten <span class="math inline">\(a\)</span> wordt opgeteld, wijzigen hun variantie en standaarddeviatie
niet.</p>
<p><strong>Einde eigenschap</strong></p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="chap-describe.html#cb159-1" aria-hidden="true"></a><span class="co"># Het gebruik van functie sd() levert de standarddeviatie</span></span>
<span id="cb159-2"><a href="chap-describe.html#cb159-2" aria-hidden="true"></a><span class="co"># van de variabele BMI in de NHANES dataset.</span></span>
<span id="cb159-3"><a href="chap-describe.html#cb159-3" aria-hidden="true"></a><span class="co"># Het na.rm=TRUE argument wordt gebruikt omdat er</span></span>
<span id="cb159-4"><a href="chap-describe.html#cb159-4" aria-hidden="true"></a><span class="co"># ontbrekende waarnemingen voorkomen.</span></span>
<span id="cb159-5"><a href="chap-describe.html#cb159-5" aria-hidden="true"></a><span class="kw">sd</span>(NHANES<span class="op">$</span>BMI,<span class="dt">na.rm=</span><span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 7.376579</code></pre>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="chap-describe.html#cb161-1" aria-hidden="true"></a> <span class="co"># levert de variantie van de variabele BMI</span></span>
<span id="cb161-2"><a href="chap-describe.html#cb161-2" aria-hidden="true"></a><span class="kw">var</span>(NHANES<span class="op">$</span>BMI,<span class="dt">na.rm=</span><span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 54.41392</code></pre>
<p>Wanneer een variabele niet Normaal verdeeld is (dit is bijvoorbeeld het
geval voor het BMI gezien het niet symmetrisch verdeeld is), dan
geldt niet langer dat bij benadering 95% van de waarnemingen ligt tussen <span class="math inline">\(\bar{x} - 2 s\)</span> en <span class="math inline">\(\bar{x} + 2 s\)</span>. Een symmetrische maat voor de spreiding
van de gegevens, zoals de standaarddeviatie, is dan niet langer interessant.
In dat geval zijn de range en interkwantielafstand betere maten.</p>

<div class="definition">
<span id="def:unnamed-chunk-103" class="definition"><strong>Definitie 4.8  (bereik en interkwartielafstand)  </strong></span>
</div>
<p>Het <strong>bereik</strong> of de <strong>range</strong> <span class="math inline">\(R_x\)</span> van een reeks waarnemingen <span class="math inline">\(x_i, i=1,2,...,n\)</span>, is per definitie het verschil tussen de grootste en
kleinste geobserveerde waarde. De <strong>interkwartielafstand</strong> van een
reeks waarnemingen <span class="math inline">\(x_i, i=1,2,...,n\)</span> is per definitie de afstand tussen het derde kwartiel <span class="math inline">\(x_{75}\)</span> en het eerste kwartiel <span class="math inline">\(x_{25}\)</span>. Dat wordt ook grafisch weergegeven op een boxplot (breedte van de box). Hierbinnen liggen circa 50% van de observaties. Circa 95% van de observaties kan men vinden tussen het 2.5% en 97.5% percentiel.</p>
<p><strong>Einde definitie</strong></p>
<p>Het bereik is zeer gevoelig voor outliers en is systematisch afhankelijk van
het aantal observaties: hoe groter <span class="math inline">\(n,\)</span> hoe groter men <span class="math inline">\(R_x\)</span> verwacht. Om
die reden vormt een interkwartielafstand een betere maat voor de spreiding
van de gegevens dan de range.</p>
<p>Tenslotte is het vaak zo dat de gegevens meer gespreid zijn naarmate hun
gemiddelde hogere waarden aanneemt. De <em>variatiecoëfficiënt</em>=<span class="math inline">\(VC_x\)</span>
standaardiseert daarom de standaarddeviatie door ze uit te drukken als een
percentage van het gemiddelde</p>
<p><span class="math display">\[\begin{equation*}
VC_x = \frac{s_x}{\bar{x}} 100\%.
\end{equation*}\]</span></p>
<p>Omdat ze gestandaardiseerd is, dient ze beter dan de standaarddeviatie zelf om de spreiding op de gegevens te vergelijken tussen populaties met een verschillend gemiddelde. De variatiecoëfficiënt heeft verder de aantrekkelijke eigenschap dat ze geen eenheden heeft en ongevoelig is
voor herschaling van de gegevens (d.w.z. wanneer alle gegevens met een
constante <span class="math inline">\(a\)</span> worden vermenigvuldigd, dan is <span class="math inline">\(VC_{ax}=VC_x\)</span>).</p>
</div>
</div>
<div id="sec:normal" class="section level2" number="4.4">
<h2><span class="header-section-number">4.4</span> De Normale benadering van gegevens</h2>
<iframe width="560" height="315" src="https://www.youtube.com/embed/_OLtgfagMTg" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen>
</iframe>
<p>Bij biologische en chemische data is het vaak zo dat het histogram van een continue
meting bij verschillende subjecten de karakteristieke vorm heeft van de
Normale verdeling. Dat is bijvoorbeeld zo als men een histogram maakt van het
logaritme van de totale cholestorol. Rond 1870 opperde de wereldberoemde
Belg Adolphe Quetelet (die tevens de eerste student was die een doctoraat behaalde aan de Universiteit
Gent) de idee om deze curve als `ideaal histogram’ te gebruiken voor de
voorstelling en vergelijking van gegevens. Dit zal handig blijken om meer
inzicht te krijgen in de gegevens op basis van een minimum aantal
samenvattingsvatten, zoals het gemiddelde en de standaarddeviatie die vaak
in wetenschappelijke rapporten vermeld staan.</p>
<div id="sec:qq" class="section level3" number="4.4.1">
<h3><span class="header-section-number">4.4.1</span> QQ-plots</h3>
<p>Hoewel heel wat metingen in de biologische wetenschappen en scheikunde, zoals
concentraties van een bepaalde stof, scheef verdeeld zijn naar rechts,
worden ze door het nemen van een logaritme vaak getransformeerd naar
gegevens waarvoor het histogram de vorm heeft van een Normale dichtheidsfunctie.
Dit is uiteraard niet altijd zo en stappen om te verifiëren of observaties
Normaal verdeeld zijn, zijn daarom van groot belang omdat heel wat technieken uit de verdere hoofdstukken er zullen van uit gaan dat de
gegevens Normaal verdeeld zijn. Hoewel een vergelijking van het histogram
van de gegevens met de vorm van de Normale curve wel inzicht geeft of de
gegevens al dan niet Normaal verdeeld zijn, is dit vaak niet makkelijk te
zien en wordt de uiteindelijke beslissing nogal makkelijk beïnvloed door de keuze
van de klassebreedtes op het histogram. Om die reden zullen we
kwantielgrafieken gebruiken die duidelijker toelaten om na te gaan of
gegevens Normaal verdeeld zijn.</p>
<p><em>QQ-plots</em> of <em>kwantielgrafieken</em> (in het Engels: <em>quantile-quantile plots</em>) zijn grafieken die toelaten te verifiëren of een
reeks observaties lukrake trekkingen zijn uit een Normale verdeling. Met
andere woorden, ze laten toe om na te gaan of een reeks observaties al dan
niet de onderstelling tegenspreken dat ze realisaties zijn van een reeks
Normaal verdeelde gegevens. Het principe achter deze grafieken is vrij
eenvoudig. Verschillende percentielen die men heeft berekend voor de gegeven
reeks observaties worden uitgezet t.o.v. de overeenkomstige percentielen die
men verwacht op basis van de Normale curve. Als de onderstelling correct is
dat de gegevens Normaal verdeeld zijn, dan komen beide percentielen telkens
vrij goed met elkaar overeen en verwacht men bijgevolg een reeks puntjes min
of meer op een rechte te zien.
Systematische afwijkingen van een rechte wijzen op systematische afwijkingen
van Normaliteit. Lukrake afwijkingen van een rechte kunnen het gevolg zijn
van toevallige biologische variatie en zijn daarom niet indicatief voor afwijkingen van
Normaliteit.</p>
<p>Om inzicht te krijgen in QQ-plots simuleren we eerst data uit de normale verdeling om te zien hoe deze plots eruit zien als de data normaal verdeeld zijn.</p>
<ul>
<li>We simuleren data voor 9 steekproeven met een gemiddeld van 18 en een standaard afwijking van 9.</li>
</ul>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="chap-describe.html#cb163-1" aria-hidden="true"></a>n &lt;-<span class="st"> </span><span class="dv">20</span></span>
<span id="cb163-2"><a href="chap-describe.html#cb163-2" aria-hidden="true"></a>mu &lt;-<span class="st"> </span><span class="dv">18</span></span>
<span id="cb163-3"><a href="chap-describe.html#cb163-3" aria-hidden="true"></a>sigma &lt;-<span class="st"> </span><span class="dv">9</span></span>
<span id="cb163-4"><a href="chap-describe.html#cb163-4" aria-hidden="true"></a>nSamp &lt;-<span class="dv">9</span></span>
<span id="cb163-5"><a href="chap-describe.html#cb163-5" aria-hidden="true"></a></span>
<span id="cb163-6"><a href="chap-describe.html#cb163-6" aria-hidden="true"></a>normSim &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">rnorm</span>(n<span class="op">*</span>nSamp,<span class="dt">mean=</span>mu,<span class="dt">sd=</span>sigma),<span class="dt">nrow=</span>n) <span class="op">%&gt;%</span><span class="st"> </span>as.data.frame</span></code></pre></div>
<p>We gaan nu de data visualiseren.</p>
<ul>
<li>Merk op dat de data niet in het tidy formaat is.</li>
<li>De data voor elke groep/simulatie staat naast elkaar in de kolommen.</li>
</ul>
<ol style="list-style-type: decimal">
<li><p>We converteren het in het tidy formaat via de <code>gather</code> functie. Hierbij wordt een eerste kolom gemaakt samp die de kolomnamen van de originele dataset normSim voor elk overeenkomstig gesimuleerd data punt bij zal houden. De inhoud van de kolommen van de originele dataset normSim, de gesimuleerde waarden, worden opgeslagen in de variable met naam data.</p></li>
<li><p>we maken een ggplot histogram voor de variabele data</p></li>
<li><p>Aan de hand van de functie <code>facet_wrap</code> kunnen we de data opsplitsen volgens de variabele samp. We krijgen dus een histogram voor elk sample.</p></li>
</ol>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="chap-describe.html#cb164-1" aria-hidden="true"></a>normSim <span class="op">%&gt;%</span></span>
<span id="cb164-2"><a href="chap-describe.html#cb164-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">gather</span>(samp,data) <span class="op">%&gt;%</span></span>
<span id="cb164-3"><a href="chap-describe.html#cb164-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>data)) <span class="op">+</span></span>
<span id="cb164-4"><a href="chap-describe.html#cb164-4" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(<span class="dt">y=</span>..density.., <span class="dt">fill=</span>..count..),<span class="dt">bins=</span><span class="dv">30</span>) <span class="op">+</span></span>
<span id="cb164-5"><a href="chap-describe.html#cb164-5" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_density</span>(<span class="kw">aes</span>(<span class="dt">y=</span>..density..)) <span class="op">+</span></span>
<span id="cb164-6"><a href="chap-describe.html#cb164-6" aria-hidden="true"></a><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span>samp)</span></code></pre></div>
<p><img src="Statistiek_2020_2021_files/figure-html/unnamed-chunk-105-1.png" width="672" /></p>
<p>Gezien er vrij weinig data punten zijn en omdat er veel distributies vergeleken moeten worden is het handiger om dit via een boxplot te doen.</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="chap-describe.html#cb165-1" aria-hidden="true"></a>normSim <span class="op">%&gt;%</span></span>
<span id="cb165-2"><a href="chap-describe.html#cb165-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">gather</span>(samp,data) <span class="op">%&gt;%</span></span>
<span id="cb165-3"><a href="chap-describe.html#cb165-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> samp,<span class="dt">y =</span> data)) <span class="op">+</span></span>
<span id="cb165-4"><a href="chap-describe.html#cb165-4" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_boxplot</span>(<span class="dt">outlier.shape=</span><span class="ot">NA</span>) <span class="op">+</span></span>
<span id="cb165-5"><a href="chap-describe.html#cb165-5" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">position=</span><span class="st">&quot;jitter&quot;</span>)</span></code></pre></div>
<p><img src="Statistiek_2020_2021_files/figure-html/unnamed-chunk-106-1.png" width="672" /></p>
<p>Hoewel alle observaties in alle steekproeven uit dezelfde populatie zijn getrokken zien we toch vrij grote fluctuaties van steekproef tot steekproef in de mediaan, maar zeker ook in de boxgrootte en het bereik van de data in elke steekproef. Dus ondanks het feit dat we over een vrij grote steekproef beschikken (20 observaties) is er toch een grote variabiliteit van steekproef tot steekproef.</p>
<p>We gaan nu normaliteit na via QQ-plot.</p>
<ol style="list-style-type: decimal">
<li>Zet data om in tidy data</li>
<li>maak een ggplot object</li>
<li>Voeg een laag toe met de QQ-plot via de functie <code>geom_qq</code></li>
<li>Voeg een laag toe met de rechte in de QQ-plot via de functie <code>geom_qq_line</code> om te kunnen evalueren hoe goed de data een normale verdeling volgt.</li>
</ol>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="chap-describe.html#cb166-1" aria-hidden="true"></a>normSim <span class="op">%&gt;%</span></span>
<span id="cb166-2"><a href="chap-describe.html#cb166-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">gather</span>(samp,data) <span class="op">%&gt;%</span></span>
<span id="cb166-3"><a href="chap-describe.html#cb166-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">sample=</span>data)) <span class="op">+</span></span>
<span id="cb166-4"><a href="chap-describe.html#cb166-4" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_qq</span>() <span class="op">+</span></span>
<span id="cb166-5"><a href="chap-describe.html#cb166-5" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_qq_line</span>() <span class="op">+</span></span>
<span id="cb166-6"><a href="chap-describe.html#cb166-6" aria-hidden="true"></a><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span>samp)</span></code></pre></div>
<p><img src="Statistiek_2020_2021_files/figure-html/unnamed-chunk-107-1.png" width="672" /></p>
<p>Zelf voor Normal data zien we duidelijk nog afwijkingen door sampling variabiliteit! De plots laten ons toe om ons visueel te trainen om QQ-plots van Normale data te herkennen.</p>
<p>Om de interpretatie van de QQ-plot goed te kunnen illustreren gaan we een histogram en QQ-plot naast elkaar zetten.
D.m.v. het package <code>gridExtra</code> kunnen we meerdere GG-plot objecten in een matrix op dezelfde plot afbeelden.</p>
<ol style="list-style-type: decimal">
<li>We maken een eerste object aan met het histogram. We slaan dit nu op als object p1 in plaats van dit te visualiseren.</li>
<li>Maak een object p2 met de QQ-plot</li>
<li>Gebruik de functie <code>grid.arrange</code> om de objecten p1 en p2 af te beelden en we geven aan dat we dit in 2 kolommen zullen doen <code>ncol=2</code>. (je kan ook de dimensie in rijen geven (nrow=1))</li>
</ol>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="chap-describe.html#cb167-1" aria-hidden="true"></a><span class="kw">library</span>(gridExtra)</span>
<span id="cb167-2"><a href="chap-describe.html#cb167-2" aria-hidden="true"></a>p1 &lt;-<span class="st"> </span>NHANES <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(Gender<span class="op">==</span><span class="st">&quot;female&quot;</span><span class="op">&amp;!</span><span class="kw">is.na</span>(BMI)) <span class="op">%&gt;%</span></span>
<span id="cb167-3"><a href="chap-describe.html#cb167-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>BMI))<span class="op">+</span></span>
<span id="cb167-4"><a href="chap-describe.html#cb167-4" aria-hidden="true"></a><span class="st">   </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(<span class="dt">y=</span>..density.., <span class="dt">fill=</span>..count..)) <span class="op">+</span></span>
<span id="cb167-5"><a href="chap-describe.html#cb167-5" aria-hidden="true"></a><span class="st">   </span><span class="kw">xlab</span>(<span class="st">&quot;BMI&quot;</span>) <span class="op">+</span></span>
<span id="cb167-6"><a href="chap-describe.html#cb167-6" aria-hidden="true"></a><span class="st">   </span><span class="kw">ggtitle</span>(<span class="st">&quot;All females in study&quot;</span>) <span class="op">+</span></span>
<span id="cb167-7"><a href="chap-describe.html#cb167-7" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_density</span>(<span class="kw">aes</span>(<span class="dt">y=</span>..density..))</span>
<span id="cb167-8"><a href="chap-describe.html#cb167-8" aria-hidden="true"></a></span>
<span id="cb167-9"><a href="chap-describe.html#cb167-9" aria-hidden="true"></a>p2 &lt;-<span class="st"> </span>NHANES <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(Gender<span class="op">==</span><span class="st">&quot;female&quot;</span><span class="op">&amp;!</span><span class="kw">is.na</span>(BMI)) <span class="op">%&gt;%</span></span>
<span id="cb167-10"><a href="chap-describe.html#cb167-10" aria-hidden="true"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">sample=</span>BMI)) <span class="op">+</span></span>
<span id="cb167-11"><a href="chap-describe.html#cb167-11" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_qq</span>() <span class="op">+</span></span>
<span id="cb167-12"><a href="chap-describe.html#cb167-12" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_qq_line</span>()</span>
<span id="cb167-13"><a href="chap-describe.html#cb167-13" aria-hidden="true"></a></span>
<span id="cb167-14"><a href="chap-describe.html#cb167-14" aria-hidden="true"></a><span class="kw">grid.arrange</span>(p1,p2,<span class="dt">ncol=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="Statistiek_2020_2021_files/figure-html/unnamed-chunk-108-1.png" width="672" /></p>
<p>The QQ-plot toont dat de kwantielen van de data in de steekproef</p>
<ul>
<li><p>groter zijn (boven de lijn liggen) dan wat we verwachten voor Normaal verdeelde data in de linkerstaart: compressie van de linkerstaart t.o.v. de Normale verdeling. De waarden in de linkerstaart liggen dus dichter bij top van de distributie dan wat we verwachten voor normaal verdeelde data.</p></li>
<li><p>groter zijn (boven de lijn liggen) dan wat we verwachten voor Normaal verdeelde data: lange staart naar rechts. De waarden in de rechterstaart liggen dus verder van de top van de distributie dan wat we verwachten voor normaal verdeelde data.</p></li>
</ul>
<p>We zien dus duidelijk dat de data scheef verdeeld zijn naar rechts.</p>
</div>
</div>
<div id="sec:explCatVar" class="section level2" number="4.5">
<h2><span class="header-section-number">4.5</span> Samenvattingsmaten voor categorische variabelen</h2>
<p>De samenvattingsmaten uit de vorige sectie (gemiddelde, mediaan, standaarddeviatie, …) kunnen niet zomaar toegepast worden voor de beschrijving van categorische variabelen. In deze sectie gaan we hier dieper op in, daarbij onderscheid makend tussen enerzijds gegevens die uit prospectieve studies of lukrake steekproeven afkomstig zijn, en anderzijds gegevens uit retrospectieve studies.</p>
<div id="prospectieve-studies-en-lukrake-steekproeven" class="section level3" number="4.5.1">
<h3><span class="header-section-number">4.5.1</span> Prospectieve studies en lukrake steekproeven</h3>

<div class="example">
<span id="exm:unnamed-chunk-109" class="example"><strong>Voorbeeld 4.3  (Houtluizen)  </strong></span>
</div>
<p>Een bioloog verzamelt `s nachts bladerafval op een lukrake plaats van 1 m<span class="math inline">\(^2\)</span>
in 2 wouden, waarvan 1 met klei- en 1 met kalkgrond. Op elke plaats telt hij het aantal houtluizen van de species
Armadilidium of Oniscus, met als doel na te gaan of de ene soort vaker voorkomt op kleigrond dan op
kalkgrond<a href="#fn18" class="footnote-ref" id="fnref18"><sup>18</sup></a>. Tabel <a href="chap-describe.html#tab:cox">4.2</a> toont de bekomen gegevens. Hier stelt <span class="math inline">\(a\)</span> (<span class="math inline">\(c\)</span>) het aantal houtluizen van de soort Armadilidium (Oniscus) voor op kleigrond, en <span class="math inline">\(b\)</span> (<span class="math inline">\(d\)</span>) het aantal houtluizen van de soort Armadilidium (Oniscus) op kalkgrond.</p>
<table>
<caption>
<span id="tab:cox">Tabel 4.2: </span>Kruistabel van species houtluis versus type grond.
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
Armadil.
</th>
<th style="text-align:left;">
Oniscus
</th>
<th style="text-align:left;">
Totaal
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Klei
</td>
<td style="text-align:left;">
14 (a)
</td>
<td style="text-align:left;">
6 (c)
</td>
<td style="text-align:left;">
20 (a+c)
</td>
</tr>
<tr>
<td style="text-align:left;">
Kalk
</td>
<td style="text-align:left;">
22 (b)
</td>
<td style="text-align:left;">
46 (d)
</td>
<td style="text-align:left;">
68 (b+d)
</td>
</tr>
<tr>
<td style="text-align:left;">
Totaal
</td>
<td style="text-align:left;">
36 (a+b)
</td>
<td style="text-align:left;">
52 (c+d)
</td>
<td style="text-align:left;">
88 (n)
</td>
</tr>
</tbody>
</table>
<p><strong>Einde voorbeeld</strong></p>
<p>Er zijn verschillende manieren om de resultaten van deze studie te
beschrijven. De kans dat 1 van beide species houtluizen van de soort Armadilidium is, is <span class="math inline">\(p_{kl}=a/(a+c)=0.70\)</span> of 70% op kleigrond en <span class="math inline">\(p_{ka}=b/(b+d)=0.32\)</span> of 32% op kalkgrond.</p>

<div class="definition">
<span id="def:unnamed-chunk-110" class="definition"><strong>Definitie 4.9  (absolute risico verschil)  </strong></span>
</div>
<p>Het <strong>absolute risico verschil</strong> of absolute kansverschil op een gegeven gebeurtenis (bvb. om Armadilidium aan te treffen) voor populatie T (Test, bvb. kleigrond) versus C (Controle, bvb. kalkgrond) wordt
met ARV genoteerd en gedefinieerd als het verschil</p>
<p><span class="math display">\[\begin{equation*}
ARV=p_T-p_C
\end{equation*}\]</span></p>
<p>tussen de kansen dat deze gebeurtenis zich voordoet in populaties T en C.</p>
<p><strong>Einde definitie</strong></p>
<p>Het ARV op Armadilidium tussen klei- en kalkgrond bedraagt 0.38, hetgeen suggereert dat de kans dat 1 van beide species houtluizen van de soort Armadilidium is, 38% hoger is op kleigrond dan op kalkgrond. Een absoluut kansverschil
van 0 drukt uit dat de overeenkomstige kansen even groot zijn in beide
populaties en dat beide populaties dus vergelijkbaar zijn in termen van de bestudeerde uitkomst.</p>
<p>Het absolute kansverschil zegt echter niet alles omtrent het
bestudeerde effect. Een kansverschil kan immers een grotere impact hebben
alnaargelang beide proporties <span class="math inline">\(p_T\)</span> en <span class="math inline">\(p_C\)</span> dicht bij 0 of 1 liggen, dan
wanneer ze in de buurt van 0.5 liggen.
Bijvoorbeeld, wanneer we de proportie
vrouwen jonger dan 60 jaar meten die borstkanker ontwikkelen, is
een risicoverschil tussen <span class="math inline">\(p_A=0.01\)</span> voor vrouwen die het allel Leu/Leu bezitten op het BRCA1 gen
en <span class="math inline">\(p_B=0.001\)</span> voor de overige vrouwen, wellicht belangrijker dan een verschil tussen <span class="math inline">\(p_C=0.41\)</span> en <span class="math inline">\(p_D=0.401\)</span> voor beide populaties. Een uitspraak dat het risico 0.9% lager is in de ene dan in de andere populatie geeft om die reden slechts een beperkt beeld van het belang van die reductie. Een goede vergelijking van risico’s, kansen of percentages moet om die reden ook rekening houden met het basisrisico (d.w.z. de kans op de bestudeerde uitkomst in een referentiepopulatie). Het ARV doet dit niet, in tegenstelling tot volgende associatiemaat.</p>

<div class="definition">
<span id="def:unnamed-chunk-111" class="definition"><strong>Definitie 4.10  (relatief risico)  </strong></span>
</div>
<p>Het <strong>relatief risico</strong> op een gegeven gebeurtenis (bvb. om Armadilidium aan te treffen) voor populatie T (Test, bvb. kleigrond) versus C (Controle, bvb. kalkgrond) wordt met RR
genoteerd en gedefinieerd als het quotiënt</p>
<p><span class="math display">\[\begin{equation*}
RR=\frac{p_T}{p_C}
\end{equation*}\]</span></p>
<p>van de kansen dat deze gebeurtenis zich voordoet in populaties T en C.</p>
<p><strong>Einde definitie</strong></p>
<p>In de studie naar houtluizen bedraagt dit <span class="math inline">\(RR=0.70/0.32=2.2\)</span>. Dit
suggereert dat er 2.2 keer zoveel kans om een houtluis van de soort Armadilidium (i.p.v. Oniscus) aan te treffen op kleigrond dan op kalkgrond. Een
relatief risico van 1 drukt uit dat beide populaties dus vergelijkbaar zijn in termen van de bestudeerde uitkomst.</p>
<p>Een nadeel van het relatief risico is dat ze, in tegenstelling tot het absolute risico verschil, niet goed duidelijk maakt hoeveel meer individuen de bestudeerde uitkomst ondervinden in de ene dan in de andere populatie. Bijvoorbeeld, zelfs wetende dat het relatief risico op Armidilidium in klei-versus kalkgrond 2.2 bedraagt, is het niet mogelijk om uit te maken hoeveel meer houtluizen van de soort Armidilidium zich manifesteren op kleigrond. Als de kans om Armidilidium aan te treffen i.p.v. Oniscus 0.1% bedraagt op kalkgrond, dan verwacht men dat er per 10000 houtluizen (van de soort Armidilidium of Oniscus) er 10 van de soort Armidilidium zullen zijn op kalkgrond en 22 op kleigrond, wat neerkomt op een verwaarloosbaar verschil van 12. Als de kans om Armidilidium aan te treffen i.p.v. Oniscus 40% bedraagt op kalkgrond, dan verwacht men dat er per 10000 houtluizen (van de soort Armidilidium of Oniscus) er 4000 van de soort Armidilidium zullen zijn op kalkgrond en 8800 op kleigrond, wat neerkomt op een aanzienlijk verschil van 4800. Soms rapporteert men in de plaats van het relatief risico, het
<em>relatieve risico verschil</em> <span class="math inline">\(ARV/p_C=RR-1\)</span>. Voor de gegeven studie
bedraagt dit 1.2. Het drukt uit dat de toename (van kalk- naar kleigrond) in kans om Armadilidium aan te treffen succes meer dan 1 keer zo groot is als het basisrisico in de controlegroep (kalkgrond).</p>
<p>Merk op dat alle bovenstaande associatiematen eveneens gebruikt kunnen
worden wanneer men, in tegenstelling tot wat in een prospectieve studie
gebeurt, een volledig lukrake groep proefpersonen selecteert zonder vast te
leggen hoeveel van hen al dan niet blootgesteld zijn.</p>
</div>
<div id="subsec:retrospect" class="section level3" number="4.5.2">
<h3><span class="header-section-number">4.5.2</span> Retrospectieve studies</h3>
<p>Beschouw de case-controle studie uit Voorbeeld <a href="chap-design.html#exm:brcaLeu">3.16</a>, waarvan
de gegevens samengevat zijn in Tabel <a href="chap-describe.html#tab:leu2">4.3</a>. Omdat men in
zo’n design op zoek gaat naar <span class="math inline">\(a+b+c\)</span> lukraak gekozen controles en <span class="math inline">\(d+e+f\)</span> lukraak
gekozen cases, liggen de marges <span class="math inline">\(a+b+c\)</span> en <span class="math inline">\(d+e+f\)</span> vast en is het bijgevolg
onmogelijk om het risico op case (bvb. risico op borstkanker) te schatten. Dit is noch mogelijk binnen de
totale groep, noch binnen de groep van blootgestelden (d.i. vrouwen met allel Leu/Leu), noch binnen de groep
niet-blootgestelden. Immers, de kans op case binnen die geobserveerde groep reflecteert hoofdzakelijk de verhouding waarin cases en controles in totaal werden gekozen door het design. Alleen analyses die de kolomtotalen
in de tabel vast gegeven veronderstellen, zijn hier zinvol. Dit heeft tot
gevolg dat <em>het relatief risico</em> op de aandoening (d.w.z. op <em>case</em>)
in de populatie voor blootgestelden versus niet-blootgestelden niet
rechtstreeks kan geschat worden op basis van gegevens uit een <em>case-controle studie</em>. Analoog kan ook het bijhorende <em>absolute risicoverschil niet geschat</em> worden.</p>
<table>
<caption>
<span id="tab:leu2">Tabel 4.3: </span>Kruistabel van borstkanker-status versus BRCA1-allel.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Genotype
</th>
<th style="text-align:left;">
Controles
</th>
<th style="text-align:left;">
Cases
</th>
<th style="text-align:left;">
Totaal
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Pro/Pro
</td>
<td style="text-align:left;">
266 (a)
</td>
<td style="text-align:left;">
342 (d)
</td>
<td style="text-align:left;">
608 (a+d)
</td>
</tr>
<tr>
<td style="text-align:left;">
Pro/Leu
</td>
<td style="text-align:left;">
250 (b)
</td>
<td style="text-align:left;">
369 (e)
</td>
<td style="text-align:left;">
619 (b+e)
</td>
</tr>
<tr>
<td style="text-align:left;">
Leu/Leu
</td>
<td style="text-align:left;">
56 (c)
</td>
<td style="text-align:left;">
89 (f)
</td>
<td style="text-align:left;">
145 (c+f)
</td>
</tr>
<tr>
<td style="text-align:left;">
Totaal
</td>
<td style="text-align:left;">
572 (a+b+c)
</td>
<td style="text-align:left;">
800 (d+e+f)
</td>
<td style="text-align:left;">
1372 (n)
</td>
</tr>
</tbody>
</table>
<p>Wel heeft men informatie over de kans om het allel Leu/Leu aan te treffen bij cases, <span class="math inline">\(\pi_1=f/(d+e+f)=89/800=11.1\%\)</span>, en de kans op het allel Leu/Leu bij controles, <span class="math inline">\(\pi_0=c/(a+b+c)=56/572=9.8\%\)</span>. Het relatief risico op blootstelling voor cases versus
controles is bijgevolg <span class="math inline">\(11.1/9.8=1.14\)</span>. Vrouwen met borstkanker hebben dus
14% meer kans om de allelcombinatie Leu/Leu te hebben op het BRCA1 gen dan vrouwen zonder borstkanker.
Dit suggereert dat er
een associatie<a href="#fn19" class="footnote-ref" id="fnref19"><sup>19</sup></a> is tussen het polymorfisme op het BRCA1 gen en borstkanker, maar drukt helaas niet uit hoeveel hoger het risico op borstkanker is voor vrouwen met de allelcombinatie Leu/Leu dan voor andere vrouwen. Om toch een antwoord te vinden op deze laatste vraag, voeren we een nieuwe risicomaat in.</p>

<div class="definition">
<span id="def:unnamed-chunk-112" class="definition"><strong>Definitie 4.11  (Odds)  </strong></span>
</div>
<p>De <em>odds</em> op een gebeurtenis wordt gedefinieerd als</p>
<p><span class="math display">\[\begin{equation*}
\frac{p}{1-p}
\end{equation*}\]</span></p>
<p>waarbij <span class="math inline">\(p\)</span> de kans is op die gebeurtenis.</p>
<p><strong>Einde definitie</strong></p>
<p>De odds is dus een transformatie van het risico, met onder andere de
volgende eigenschappen:</p>
<ul>
<li><p>de odds neemt waarden aan tussen nul en oneindig.</p></li>
<li><p>de odds is gelijk aan 1 als en slechts als de kans zelf gelijk is aan
1/2.</p></li>
<li><p>de odds neemt toe als de kans toeneemt.</p></li>
</ul>
<p>Het gebruik van odds is populair onder gokkers omdat het uitdrukt hoeveel
waarschijnlijker het is om te winnen dan om te verliezen. Een odds op winnen
gelijk aan 1 drukt bijvoorbeeld uit dat het even waarschijnlijk is om te
winnen dan om te verliezen. Een odds op winnen gelijk aan 0.9 drukt uit men
per 10 verliesbeurten, 9 keer verwacht te winnen. In de genetische associatiestudie uit Voorbeeld <a href="chap-design.html#exm:brcaLeu">3.16</a>
is de odds op allel Leu/Leu bij cases gelijk aan
<span class="math inline">\(\mbox{odds}_1=f/(d+e)=89/711=0.125\)</span> en bij controles gelijk aan <span class="math inline">\(\mbox{odds}_2=c/(a+b)=56/516=0.109\)</span>. Vrouwen met borstkanker hebben bijgevolg ongeveer 8 (<span class="math inline">\(\approx 1/0.125\)</span>) keer meer kans om de allelcombinatie Leu/Leu niet te hebben op het BRCA1 gen dan om het wel te hebben.
Om de associatie tussen blootstelling
en uitkomst te beschrijven, kan men nu een verhouding van odds (odds ratio)
gebruiken in plaats van een verhouding van risico’s (relatief risico).</p>

<div class="definition">
<span id="def:unnamed-chunk-113" class="definition"><strong>Definitie 4.12  (Odds ratio)  </strong></span>
</div>
<p>De <strong>odds ratio</strong> op een gegeven gebeurtenis (bvb. borstkanker) voor populatie T (bvb. vrouwen met allel Leu/Leu) versus C (bvb. vrouwen zonder allel Leu/Leu) wordt met OR genoteerd en gedefinieerd als het quotiënt
<span class="math display">\[\begin{equation*}
OR=\frac{\mbox{odds}_T}{\mbox{odds}_C}
\end{equation*}\]</span>
van de odds op deze gebeurtenis in populaties T en C.</p>
<p><strong>Einde definitie</strong></p>
<p>Op basis van de gegevens in Tabel <a href="chap-describe.html#tab:leu2">4.3</a> kan de odds ratio op
blootstelling voor cases versus controles geschat worden d.m.v. het kruisproduct</p>
<p><span class="math display">\[\begin{equation*}
\frac{ \frac{ f/(d+e+f)}{(d+e)/(d+e+f)} }{ \frac{c/(a+b+c)}{(a+b)/(a+b+c)}} = \frac{f(a+b)}{c (d+e)}
\end{equation*}\]</span></p>
<p>In het bijzonder vinden we dat de odds op allelcombinatie Leu/Leu voor vrouwen met versus zonder borstkanker gelijk is aan <span class="math inline">\(OR=(89\times 516)/(56\times 711)=1.15\)</span>. Helaas drukt dit resultaat nog steeds
niet uit hoeveel meer risico op borstkanker vrouwen met de allelcombinatie Leu/Leu lopen.</p>
<p>Was de bovenstaande studie echter een volledig lukrake steekproef geweest
(waarbij het aantal cases en controles niet per design werden vastgelegd),
dan konden we daar ook de odds ratio op borstkanker berekenen voor mensen
met versus zonder het allel Leu/leu. We zouden dan vaststellen dat dit gelijk is
aan</p>
<p><span class="math display">\[\begin{equation*}
\frac{ \frac{ f/(c+f)}{c/(c+f)} }{ \frac{(d+e)/(a+b+d+e)}{(a+b)/(a+b+d+e)}} = \frac{f(a+b)}{c(d+e)},
\end{equation*}\]</span></p>
<p>en bijgevolg dezelfde waarde aanneemt. Dat is omdat de odds ratio een
<em>symmetrische associatiemaat</em> is zodat de odds ratio op `case’ voor
blootgestelden versus niet-blootgestelden steeds gelijk is aan de odds op
blootstelling voor cases versus controles. Hieruit volgt dat voor het
schatten van de odds ratio het er niet toe doet of we prospectief werken
zoals in een typische cohort studie, of retrospectief zoals in een typische
case-controle studie. In het bijzonder kunnen we in de genetische associatiestudie uit
Voorbeeld <a href="chap-design.html#exm:brcaLeu">3.16</a> de odds op borstkanker voor vrouwen met allel Leu/leu
versus zonder berekenen als <span class="math inline">\(OR=89\times 516/(56\times 711)=1.15\)</span>.
De odds op borstkanker is bijgevolg 15% hoger bij vrouwen met die specifieke allelcombinatie.</p>
<p>Stel nu dat we met <span class="math inline">\(p_T\)</span> en <span class="math inline">\(p_C\)</span> respectievelijk de kans op case noteren
voor blootgestelden en niet-blootgestelden. Wanneer beide kansen klein zijn
(namelijk <span class="math inline">\(p_T&lt;5\%\)</span> en <span class="math inline">\(p_C&lt;5\%\)</span>), dan is de odds een goede benadering voor
het risico. Dit is omdat in dat geval <span class="math inline">\(\mbox{odds}_T=p_T/(1-p_T)\approx p_T\)</span> en <span class="math inline">\(\mbox{odds}_C=p_C/(1-p_C)\approx p_C\)</span>. Er volgt dan bovendien dat de odds ratio
een goede benadering voor het relatief risico:</p>
<p><span class="math display">\[\begin{equation*}
OR=\frac{\mbox{ odds}_T}{\mbox{
odds}_C}\approx \frac{p_T}{p_C}=RR
\end{equation*}\]</span></p>
<p>Wetende dat het risico op borstkanker laag is, mogen we
op basis van de gevonden OR van 1.15 bijgevolg
besluiten dat het risico (i.p.v. de odds) op borstkanker (bij benadering) 15% hoger ligt bij vrouwen met het allel Leu/Leu op het BRCA1 gen. Dit is een bijzonder
nuttige eigenschap omdat (a) het relatief risico, dat niet rechtstreeks
geschat kan worden in case-controle studies, gemakkelijker te interpreteren
is dan de odds ratio; en (b) de odds ratio bepaalde wiskundige eigenschappen
heeft die ze aantrekkelijker maakt dan een relatief risico in statistische
modellen<a href="#fn20" class="footnote-ref" id="fnref20"><sup>20</sup></a>. Algemeen is de odds ratio echter steeds verder van 1 verwijderd
dan het relatief risico. Wetende dat de odds ratio op borstkanker 1.15
bedraagt voor vrouwen met versus zonder de allelcombinatie Leu/Leu, kunnen we bijgevolg meer
nauwkeurig besluiten dat het overeenkomstige relatief risico tussen 1 en 1.15
gelegen is (maar niettemin dicht bij 1.15).</p>
<p>Omdat de odds ratio moeilijker te interpreteren is dan een relatief risico
en bijgevolg misleidend kan zijn, valt deze laatste steeds te verkiezen in
situaties (zoals prospectieve studies) waar het mogelijk is om het relatief
risico in de populatie te schatten. In sommige case-controle studies (nl.
matched case-controle studies) wordt voor elke case een controle gezocht die
bepaalde karakteristieken gemeenschappelijk heeft, teneinde een betere
onderlinge vergelijkbaarheid te garanderen. In dat geval moet de
statistische analyse (inclusief de manier om odds ratio’s te schatten)
rekening houden met het feit dat de resultaten van elke case gecorreleerd of
verwant zijn met de resultaten van de bijhorende controle.</p>
</div>
<div id="rates-versus-risicos" class="section level3" number="4.5.3">
<h3><span class="header-section-number">4.5.3</span> Rates versus risico’s</h3>
<p>Vaak wordt het begrip <em>risico</em> verward met het begrip <em>rate</em>. Een
<em>rate</em> drukt een aantal gebeurtenissen (bvb. aantal sterfte- of
ziektegevallen) uit per eenheid in de populatie in een bepaalde tijdspanne.
Bijvoorbeeld, een <em>crude mortality rate (CMR)</em> voor een bepaald
jaartal is gedefinieerd als 1000 maal het aantal sterftegevallen dat
optreedt in dat jaar gedeeld door de grootte van de beschouwde populatie
halfweg dat jaar. De reden dat met 1000 wordt vermenigvuldigd is dat het
bijvoorbeeld makkelijker na te denken is over een CMR van 12 sterftes per
1000 in Engeland en Wales, dan over 0.012 sterftes per individu. Indien een
specifieke leeftijdsgroep wordt gekozen, verkrijgt men de <em>leeftijdsspecifieke mortality rate</em> als 1000 maal het aantal sterftegevallen
dat optreedt in een bepaald jaar en bepaalde leeftijdsgroep gedeeld door de
grootte van de beschouwde populatie in die leeftijdsklasse halfweg dat jaar.
In tegenstelling tot de incidentie, is de prevalentie geen rate omdat ze
niet een aantal gebeurtenissen uitdrukt over een zekere tijdspanne.</p>
</div>
</div>
<div id="associaties-tussen-twee-variabelen" class="section level2" number="4.6">
<h2><span class="header-section-number">4.6</span> Associaties tussen twee variabelen</h2>
<p>Tot nog toe zijn we hoofdzakelijk ingegaan op zogenaamde univariate beschrijvingen waarbij slechts 1 variabele onderzocht wordt. In de meeste wetenschappelijke studies wenst men echter associaties tussen 2 of meerdere variabelen te onderzoeken, bijvoorbeeld tussen een interventie en de daarop volgende respons. In deze Sectie onderzoeken we hoe associaties tussen 2 variabelen kunnen beschreven worden. We maken daarbij onderscheid naargelang het type van de variabelen.</p>
<div id="subsec:kruistabel" class="section level3" number="4.6.1">
<h3><span class="header-section-number">4.6.1</span> Associatie tussen twee kwalitatieve variabelen</h3>
<p>Als twee kwalitatieve variabelen niet veel verschillende waarden aannemen,
dan is een <em>kruistabel</em> aangewezen om hun associatie voor te stellen.
In deze tabel worden de verschillende waarden die de ene variabele aanneemt
in de kolommen uitgezet en de verschillende waarden die de andere variabele
aanneemt in de rijen. In elke cel van de tabel (die overeenkomt met 1
specifieke combinatie van waarden voor beide variabelen) wordt de frequentie
neergeschreven.</p>
<table>
<caption>
<span id="tab:genderBMI">Tabel 4.4: </span>Kruistabel van Gender vs BMI klasse.
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
12.0_18.5
</th>
<th style="text-align:right;">
18.5_to_24.9
</th>
<th style="text-align:right;">
25.0_to_29.9
</th>
<th style="text-align:right;">
30.0_plus
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
female
</td>
<td style="text-align:right;">
629
</td>
<td style="text-align:right;">
1616
</td>
<td style="text-align:right;">
1179
</td>
<td style="text-align:right;">
1402
</td>
</tr>
<tr>
<td style="text-align:left;">
male
</td>
<td style="text-align:right;">
648
</td>
<td style="text-align:right;">
1295
</td>
<td style="text-align:right;">
1485
</td>
<td style="text-align:right;">
1349
</td>
</tr>
</tbody>
</table>
<p>Tabel <a href="chap-describe.html#tab:genderBMI">4.4</a> toont zo’n kruistabel voor het aantal mannen en vrouwen per BMI klasse. Dergelijke eenvoudige kruistabel met slechts 2 rijen en 4 kolommen, noemt men ook een <span class="math inline">\(2\times 4\)</span> tabel.</p>
</div>
<div id="subsec:asskwalcont" class="section level3" number="4.6.2">
<h3><span class="header-section-number">4.6.2</span> Associatie tussen één kwalitatieve en één continue variabele</h3>
<p>Boxplots zijn meer compact dan een histogram en laat om die reden gemakkelijker vergelijkingen tussen verschillende groepen toe. Twee dergelijke boxplots
worden getoond in Figuur <a href="chap-describe.html#fig:boxplotCholGender">4.5</a>.</p>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb168-1"><a href="chap-describe.html#cb168-1" aria-hidden="true"></a>NHANES <span class="op">%&gt;%</span></span>
<span id="cb168-2"><a href="chap-describe.html#cb168-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Gender,<span class="dt">y =</span> <span class="kw">log</span>(DirectChol))) <span class="op">+</span></span>
<span id="cb168-3"><a href="chap-describe.html#cb168-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_boxplot</span>() <span class="op">+</span></span>
<span id="cb168-4"><a href="chap-describe.html#cb168-4" aria-hidden="true"></a><span class="st">  </span><span class="kw">ylab</span>(<span class="st">&quot;log(Direct Cholestorol)&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:boxplotCholGender"></span>
<img src="Statistiek_2020_2021_files/figure-html/boxplotCholGender-1.png" alt="Boxplot van log-getransformeerde directe HDL cholestorol concentratie in functie van Gender voor alle subjecten van de NHANES studie." width="100%" />
<p class="caption">
Figuur 4.5: Boxplot van log-getransformeerde directe HDL cholestorol concentratie in functie van Gender voor alle subjecten van de NHANES studie.
</p>
</div>
<p>Op basis van deze figuur
stellen we vast dat hogere log-cholestorol concentraties
geobserveerd worden bij vrouwen dan bij mannen, maar dat de variabiliteit
van de log-concentraties vergelijkbaar is tussen de 2 groepen. De vraag blijft of we hier kunnen spreken van een systematisch hogere
log-cholestorol concentratie tussen vrouwen en mannen. We zullen in Hoofdstuk <a href="chap-besluit.html#chap:besluit">5</a> dieper op deze vraag ingaan.</p>
<p>Figuur <a href="chap-describe.html#fig:boxplotCholGender">4.5</a> kan men samenvatten door gemiddelde verschillen tussen beide groepen te rapporteren. Hier stellen we een gemiddeld verschil van 0.17 in directe HDL cholestorol concentratie vast op de log schaal tussen vrouwen en mannen.
Gezien we weten dat <span class="math inline">\(\log(C_2)-\log(C_1)=\log(C_2/C_1)\)</span> weten we dat de HDL cholestorol concentratie in de NHANES studie gemiddeld 1.19 keer hoger ligt voor vrouwen dan voor mannen.</p>
<p>In de introductie hebben we bij het microbiome voorbeeld gezien dat het ook erg nuttig is om de ruwe data weer te geven op de boxplot. Als het aantal gegevens niet te hoog is kunnen we eenvoudig een extra laag toevoegen met de originele datapunten. Merk op dat het wel belangrijk is om de outliers dan niet weer te geven in de boxplot, anders zal men deze twee keer afbeelden. Eens in de geom_boxplot laag een eens in de geom_point laag. Daarom zetten we het symbool voor de outliers op NA.</p>
<p>In onderstaande grafiek plotten we de relatieve abundanties van <strong>Staphylococcus</strong> van de oksel microbiome case study.</p>
<ol style="list-style-type: decimal">
<li>We pipen het <code>ap</code> dataframe naar <code>ggplot</code></li>
<li>We selecteren de data voor de plot via <code>ggplot(aes(x=trt,y=rel))</code></li>
<li>We voegen laag toe voor de boxplot dmv de functie <code>geom_boxplot()</code>. Merk op dat we het argument <code>outlier.shape</code> op NA (not available) zetten <code>outlier.shape=NA</code> in the <code>geom_boxplot</code> functie omdat we anders outliers twee keer weer zullen geven. Eerst via de boxplot laag en daarna omdat we een laag met alle ruwe data toevoegen aan de plot.</li>
<li>We geven de ruwe data weer via de <code>geom_point(position="jitter")</code> functie. We gebruiken hierbij het argument position=‘jitter’ zodat we wat random ruis toevoegen aan de x-cordinaat zodat de gegevens elkaar niet overlappen.</li>
</ol>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="chap-describe.html#cb169-1" aria-hidden="true"></a>ap &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;https://raw.githubusercontent.com/GTPB/PSLS20/master/data/armpit.csv&quot;</span>)</span>
<span id="cb169-2"><a href="chap-describe.html#cb169-2" aria-hidden="true"></a></span>
<span id="cb169-3"><a href="chap-describe.html#cb169-3" aria-hidden="true"></a>ap <span class="op">%&gt;%</span><span class="st">  </span></span>
<span id="cb169-4"><a href="chap-describe.html#cb169-4" aria-hidden="true"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>trt,<span class="dt">y=</span>rel)) <span class="op">+</span></span>
<span id="cb169-5"><a href="chap-describe.html#cb169-5" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_boxplot</span>(<span class="dt">outlier.shape=</span><span class="ot">NA</span>) <span class="op">+</span></span>
<span id="cb169-6"><a href="chap-describe.html#cb169-6" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">position=</span><span class="st">&quot;jitter&quot;</span>)</span></code></pre></div>
<p><img src="Statistiek_2020_2021_files/figure-html/unnamed-chunk-114-1.png" width="672" /></p>
<p>Dot-plots zijn bijzonder interessant in pre-test post-test designs waar dezelfde subjecten op
verschillende tijdstippen worden geobserveerd. In dat geval kunnen de uitkomsten
uitgezet worden op de Y-as en de tijdstippen op de X-as, en kunnen de
metingen voor eenzelfde subject worden verbonden met een lijn.</p>
<p>Een
voorbeeld hiervan is weergegeven in Figuur <a href="chap-describe.html#fig:captoDot">4.6</a>. De figuur vat de gegevens samen van de captopril studie die de centrale dataset vormt van Hoofdstuk <a href="chap-besluit.html#chap:besluit">5</a>. In de studie wenst men het effect van een bloeddrukverlagend geneesmiddel captopril evalueren. Voor elke patiënt in de studie werd de systolische bloeddruk twee keer gemeten: één keer voor en één keer na de behandeling met het bloeddruk verlagende medicijn captopril. In Figuur <a href="chap-describe.html#fig:captoDot">4.6</a> worden de metingen van dezelfde patiënt met een lijntje verbonden. Hierdoor krijgen we een heel duidelijk beeld van de gegevens. Namelijk, we krijgen een sterke indruk dat de bloeddruk daalt na het toedienen van captopril gezien we bijna voor alle patiënten een daling observeren.</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="chap-describe.html#cb170-1" aria-hidden="true"></a><span class="co">#Eerst lezen we de data in.</span></span>
<span id="cb170-2"><a href="chap-describe.html#cb170-2" aria-hidden="true"></a><span class="co">#Deze bevindt zich in de subdirectory dataset</span></span>
<span id="cb170-3"><a href="chap-describe.html#cb170-3" aria-hidden="true"></a><span class="co">#Het is een tekstbestand waarbij de kolommen van elkaar gescheiden zijn d.m.v comma&#39;s.</span></span>
<span id="cb170-4"><a href="chap-describe.html#cb170-4" aria-hidden="true"></a><span class="co">#sep=&quot;,&quot;</span></span>
<span id="cb170-5"><a href="chap-describe.html#cb170-5" aria-hidden="true"></a><span class="co">#De eerste rij bevat de namen van de variabelen</span></span>
<span id="cb170-6"><a href="chap-describe.html#cb170-6" aria-hidden="true"></a>captopril &lt;-<span class="st"> </span><span class="kw">read.table</span>(<span class="st">&quot;https://raw.githubusercontent.com/statOmics/sbc20/master/data/captopril.txt&quot;</span>,<span class="dt">header=</span><span class="ot">TRUE</span>,<span class="dt">sep=</span><span class="st">&quot;,&quot;</span>)</span>
<span id="cb170-7"><a href="chap-describe.html#cb170-7" aria-hidden="true"></a><span class="kw">head</span>(captopril)</span></code></pre></div>
<pre><code>##   id SBPb DBPb SBPa DBPa
## 1  1  210  130  201  125
## 2  2  169  122  165  121
## 3  3  187  124  166  121
## 4  4  160  104  157  106
## 5  5  167  112  147  101
## 6  6  176  101  145   85</code></pre>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="chap-describe.html#cb172-1" aria-hidden="true"></a>captoprilTidy &lt;-</span>
<span id="cb172-2"><a href="chap-describe.html#cb172-2" aria-hidden="true"></a><span class="st">  </span>captopril <span class="op">%&gt;%</span></span>
<span id="cb172-3"><a href="chap-describe.html#cb172-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">gather</span>(type,bp,<span class="op">-</span>id)</span>
<span id="cb172-4"><a href="chap-describe.html#cb172-4" aria-hidden="true"></a></span>
<span id="cb172-5"><a href="chap-describe.html#cb172-5" aria-hidden="true"></a>captoprilTidy <span class="op">%&gt;%</span></span>
<span id="cb172-6"><a href="chap-describe.html#cb172-6" aria-hidden="true"></a><span class="st">  </span><span class="kw">filter</span>(type<span class="op">%in%</span><span class="kw">c</span>(<span class="st">&quot;SBPa&quot;</span>,<span class="st">&quot;SBPb&quot;</span>)) <span class="op">%&gt;%</span></span>
<span id="cb172-7"><a href="chap-describe.html#cb172-7" aria-hidden="true"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">type =</span> <span class="kw">factor</span>(</span>
<span id="cb172-8"><a href="chap-describe.html#cb172-8" aria-hidden="true"></a>    type,</span>
<span id="cb172-9"><a href="chap-describe.html#cb172-9" aria-hidden="true"></a>    <span class="dt">levels =</span> <span class="kw">c</span>(<span class="st">&quot;SBPb&quot;</span>,<span class="st">&quot;SBPa&quot;</span>))</span>
<span id="cb172-10"><a href="chap-describe.html#cb172-10" aria-hidden="true"></a>    ) <span class="op">%&gt;%</span></span>
<span id="cb172-11"><a href="chap-describe.html#cb172-11" aria-hidden="true"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>type,<span class="dt">y=</span>bp)) <span class="op">+</span></span>
<span id="cb172-12"><a href="chap-describe.html#cb172-12" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">group =</span> id)) <span class="op">+</span></span>
<span id="cb172-13"><a href="chap-describe.html#cb172-13" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_point</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:captoDot"></span>
<img src="Statistiek_2020_2021_files/figure-html/captoDot-1.png" alt="Dotplot van de systolische bloeddruk in de captopril studie voor en na het toedienen van het bloeddruk verlagend middel captopril." width="100%" />
<p class="caption">
Figuur 4.6: Dotplot van de systolische bloeddruk in de captopril studie voor en na het toedienen van het bloeddruk verlagend middel captopril.
</p>
</div>
</div>
</div>
<div id="sec:correlatie" class="section level2" number="4.7">
<h2><span class="header-section-number">4.7</span> Associatie tussen twee continue variabelen</h2>
<iframe width="560" height="315" src="https://www.youtube.com/embed/_1SD8DTCLAU" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen>
</iframe>
<p>We zullen dit opnieuw illustreren aan de hand van de NHANES studie. We bestuderen hierbij lengte en gewicht bij vrouwen.</p>
<p>We voeren eerst een data exploratie uit waarbij we</p>
<ol style="list-style-type: decimal">
<li>De volwassen vrouwen filteren uit de dataset</li>
<li>In het ggplot commando de lengte selecteren in de x-as en het gewicht in de y-as.</li>
<li>Een laag toevoegen d.m.v. <code>geom_point</code> om een scatterplot te bekomen van y i.f.v. x.</li>
</ol>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="chap-describe.html#cb173-1" aria-hidden="true"></a>NHANES<span class="op">%&gt;%</span></span>
<span id="cb173-2"><a href="chap-describe.html#cb173-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">filter</span>(Age <span class="op">&gt;=</span><span class="st"> </span><span class="dv">18</span> <span class="op">&amp;</span><span class="st"> </span>Gender<span class="op">==</span><span class="st">&quot;female&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb173-3"><a href="chap-describe.html#cb173-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>Height,<span class="dt">y=</span>Weight)) <span class="op">+</span></span>
<span id="cb173-4"><a href="chap-describe.html#cb173-4" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_point</span>()</span></code></pre></div>
<p><img src="Statistiek_2020_2021_files/figure-html/unnamed-chunk-115-1.png" width="672" /></p>
<p>Er is een duidelijke associatie tussen gewicht en lengte: als de lengte stijgt dan stijgt het gewicht gemiddeld ook. Er is echter veel variabiliteit en ook een indicatie dat het gewicht is scheef verdeeld naar rechts.</p>
<p>We exploreren eerst de data univariaat: variabele per variabele. Om een histogram en QQ-plot naast elkaar af te beelden slaan we de plots eerst op als een object en maken we gebruik van de <code>grid.arrange</code> functie van het gridExtra package om de plots naast elkaar te plotten.</p>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb174-1"><a href="chap-describe.html#cb174-1" aria-hidden="true"></a>p1 &lt;-<span class="st"> </span>NHANES<span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(Age <span class="op">&gt;=</span><span class="st"> </span><span class="dv">18</span> <span class="op">&amp;</span><span class="st"> </span>Gender<span class="op">==</span><span class="st">&quot;female&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb174-2"><a href="chap-describe.html#cb174-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>Height)) <span class="op">+</span></span>
<span id="cb174-3"><a href="chap-describe.html#cb174-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(<span class="dt">y=</span>..density.., <span class="dt">fill=</span>..count..)) <span class="op">+</span></span>
<span id="cb174-4"><a href="chap-describe.html#cb174-4" aria-hidden="true"></a><span class="st">   </span><span class="kw">xlab</span>(<span class="st">&quot;Height&quot;</span>) <span class="op">+</span></span>
<span id="cb174-5"><a href="chap-describe.html#cb174-5" aria-hidden="true"></a><span class="st">  </span><span class="kw">ggtitle</span>(<span class="st">&quot;All females in study&quot;</span>) <span class="op">+</span></span>
<span id="cb174-6"><a href="chap-describe.html#cb174-6" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_density</span>(<span class="kw">aes</span>(<span class="dt">y=</span>..density..))</span>
<span id="cb174-7"><a href="chap-describe.html#cb174-7" aria-hidden="true"></a></span>
<span id="cb174-8"><a href="chap-describe.html#cb174-8" aria-hidden="true"></a>p2 &lt;-<span class="st"> </span>NHANES<span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(Age <span class="op">&gt;=</span><span class="st"> </span><span class="dv">18</span> <span class="op">&amp;</span><span class="st"> </span>Gender<span class="op">==</span><span class="st">&quot;female&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb174-9"><a href="chap-describe.html#cb174-9" aria-hidden="true"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">sample=</span>Height)) <span class="op">+</span></span>
<span id="cb174-10"><a href="chap-describe.html#cb174-10" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_qq</span>() <span class="op">+</span></span>
<span id="cb174-11"><a href="chap-describe.html#cb174-11" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_qq_line</span>()</span>
<span id="cb174-12"><a href="chap-describe.html#cb174-12" aria-hidden="true"></a><span class="kw">grid.arrange</span>(p1,p2,<span class="dt">ncol=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="Statistiek_2020_2021_files/figure-html/unnamed-chunk-116-1.png" width="672" /></p>
<p>De lengte data zijn duidelijk approximatief normaal verdeeld.</p>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb175-1"><a href="chap-describe.html#cb175-1" aria-hidden="true"></a>p3 &lt;-<span class="st"> </span>NHANES<span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(Age <span class="op">&gt;=</span><span class="st"> </span><span class="dv">18</span> <span class="op">&amp;</span><span class="st"> </span>Gender<span class="op">==</span><span class="st">&quot;female&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb175-2"><a href="chap-describe.html#cb175-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>Weight)) <span class="op">+</span></span>
<span id="cb175-3"><a href="chap-describe.html#cb175-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(<span class="dt">y=</span>..density.., <span class="dt">fill=</span>..count..)) <span class="op">+</span></span>
<span id="cb175-4"><a href="chap-describe.html#cb175-4" aria-hidden="true"></a><span class="st">   </span><span class="kw">xlab</span>(<span class="st">&quot;Weight&quot;</span>) <span class="op">+</span></span>
<span id="cb175-5"><a href="chap-describe.html#cb175-5" aria-hidden="true"></a><span class="st">  </span><span class="kw">ggtitle</span>(<span class="st">&quot;All females in study&quot;</span>) <span class="op">+</span></span>
<span id="cb175-6"><a href="chap-describe.html#cb175-6" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_density</span>(<span class="kw">aes</span>(<span class="dt">y=</span>..density..))</span>
<span id="cb175-7"><a href="chap-describe.html#cb175-7" aria-hidden="true"></a></span>
<span id="cb175-8"><a href="chap-describe.html#cb175-8" aria-hidden="true"></a>p4 &lt;-<span class="st"> </span>NHANES<span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(Age <span class="op">&gt;=</span><span class="st"> </span><span class="dv">18</span> <span class="op">&amp;</span><span class="st"> </span>Gender<span class="op">==</span><span class="st">&quot;female&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb175-9"><a href="chap-describe.html#cb175-9" aria-hidden="true"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">sample=</span>Weight)) <span class="op">+</span></span>
<span id="cb175-10"><a href="chap-describe.html#cb175-10" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_qq</span>() <span class="op">+</span></span>
<span id="cb175-11"><a href="chap-describe.html#cb175-11" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_qq_line</span>()</span>
<span id="cb175-12"><a href="chap-describe.html#cb175-12" aria-hidden="true"></a></span>
<span id="cb175-13"><a href="chap-describe.html#cb175-13" aria-hidden="true"></a><span class="kw">grid.arrange</span>(p3,p4,<span class="dt">ncol=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="Statistiek_2020_2021_files/figure-html/unnamed-chunk-117-1.png" width="672" /></p>
<p>De gewichtsdata zijn inderdaad scheef verdeeld!</p>
<p>Na log transformatie zijn de gewichtsdata minder scheef, maar nog steeds niet Normaal verdeeld.</p>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb176-1"><a href="chap-describe.html#cb176-1" aria-hidden="true"></a>p5 &lt;-<span class="st"> </span>NHANES<span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(Age <span class="op">&gt;=</span><span class="st"> </span><span class="dv">18</span> <span class="op">&amp;</span><span class="st"> </span>Gender<span class="op">==</span><span class="st">&quot;female&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb176-2"><a href="chap-describe.html#cb176-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>Weight<span class="op">%&gt;%</span>log2)) <span class="op">+</span></span>
<span id="cb176-3"><a href="chap-describe.html#cb176-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(<span class="dt">y=</span>..density.., <span class="dt">fill=</span>..count..)) <span class="op">+</span></span>
<span id="cb176-4"><a href="chap-describe.html#cb176-4" aria-hidden="true"></a><span class="st">   </span><span class="kw">xlab</span>(<span class="st">&quot;Weight (log2)&quot;</span>) <span class="op">+</span></span>
<span id="cb176-5"><a href="chap-describe.html#cb176-5" aria-hidden="true"></a><span class="st">  </span><span class="kw">ggtitle</span>(<span class="st">&quot;All females in study&quot;</span>) <span class="op">+</span></span>
<span id="cb176-6"><a href="chap-describe.html#cb176-6" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_density</span>(<span class="kw">aes</span>(<span class="dt">y=</span>..density..))</span>
<span id="cb176-7"><a href="chap-describe.html#cb176-7" aria-hidden="true"></a></span>
<span id="cb176-8"><a href="chap-describe.html#cb176-8" aria-hidden="true"></a>p6&lt;-<span class="st"> </span>NHANES<span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(Age <span class="op">&gt;=</span><span class="st"> </span><span class="dv">18</span> <span class="op">&amp;</span><span class="st"> </span>Gender<span class="op">==</span><span class="st">&quot;female&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb176-9"><a href="chap-describe.html#cb176-9" aria-hidden="true"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">sample=</span>Weight<span class="op">%&gt;%</span>log2)) <span class="op">+</span></span>
<span id="cb176-10"><a href="chap-describe.html#cb176-10" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_qq</span>() <span class="op">+</span></span>
<span id="cb176-11"><a href="chap-describe.html#cb176-11" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_qq_line</span>()</span>
<span id="cb176-12"><a href="chap-describe.html#cb176-12" aria-hidden="true"></a></span>
<span id="cb176-13"><a href="chap-describe.html#cb176-13" aria-hidden="true"></a><span class="kw">grid.arrange</span>(p5,p6,<span class="dt">ncol=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="Statistiek_2020_2021_files/figure-html/unnamed-chunk-118-1.png" width="672" /></p>
<p>De scheefheid is er nog maar is sterk gereduceerd. We maken nu een plot van lengte in functie van het log<span class="math inline">\(_2\)</span> getransformeerde gewicht.</p>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="chap-describe.html#cb177-1" aria-hidden="true"></a>NHANES<span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(Age <span class="op">&gt;=</span><span class="st"> </span><span class="dv">18</span> <span class="op">&amp;</span><span class="st"> </span>Gender<span class="op">==</span><span class="st">&quot;female&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb177-2"><a href="chap-describe.html#cb177-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>Height,<span class="dt">y=</span>Weight <span class="op">%&gt;%</span><span class="st"> </span>log2)) <span class="op">+</span></span>
<span id="cb177-3"><a href="chap-describe.html#cb177-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">ylab</span>(<span class="st">&quot;Weight (log2)&quot;</span>) <span class="op">+</span></span>
<span id="cb177-4"><a href="chap-describe.html#cb177-4" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_point</span>()</span></code></pre></div>
<p><img src="Statistiek_2020_2021_files/figure-html/unnamed-chunk-119-1.png" width="672" /></p>
<p>We introduceren nu een statistiek om de associatie te schatten: de correlatie.</p>
<!---break-->
<div id="covariantie-en-correlatie" class="section level3" number="4.7.1">
<h3><span class="header-section-number">4.7.1</span> Covariantie en Correlatie</h3>
<iframe width="560" height="315" src="https://www.youtube.com/embed/uhvEMOfGq4c" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen>
</iframe>
<p>Stel dat X en Y continue toevallig veranderlijken zijn</p>
<ul>
<li>Voor elk subject i observeren we dus <span class="math inline">\((X_i,Y_i)\)</span>.</li>
<li>Covariantie: hoe variëren <span class="math inline">\(X_i\)</span> en <span class="math inline">\(Y_i\)</span> rond hun gemiddelde <span class="math inline">\((E[X],E[Y])\)</span>?</li>
</ul>
<p><span class="math display">\[\mbox{Covar}(X,Y)=E[(X-E[X])(Y-E[Y])]\]</span></p>
<ul>
<li>De covariantie is dus de verwachte waarde van het product van de afwijking van de X waarde t.o.v. zijn verwachte waarde E[X] en de afwijking van de Y waarde t.o.v.zijn verwachte waarde E[Y].</li>
</ul>
<p>We kunnen de covariantie nu ook standardiseren zodat we een maat krijgen die voor elke dataset vergelijkbaar wordt: de correlatie. We doen dit door de covariantie te delen door de standaardafwijking van elke variabele:</p>
<p><span class="math display">\[\mbox{Cor}(X,Y)=\frac{E[(X-E[X])(Y-E[Y])]}{\sqrt{E[(X-E[X])^2}\sqrt{E[(Y-E[Y])^2}}\]</span></p>
</div>
<div id="pearson-correlatie" class="section level3" number="4.7.2">
<h3><span class="header-section-number">4.7.2</span> Pearson Correlatie</h3>
<p>We introduceren nu een schatter voor de correlatie tussen twee continue toevallig veranderlijken op basis van de data in de steekproef:</p>
<p><span class="math display">\[
\mbox{Cor}(X,Y)=\frac{\sum_{i=1}^{n}(x_{i}-\bar{x})(y_{i}-\bar{y})}{(n-1)s_{x}s_{y}}
\]</span></p>
<p>We vervangen de verwachte waarden weer door het steekproefgemiddelden <span class="math inline">\(\bar x\)</span> en <span class="math inline">\(\bar y\)</span>, en, we berekenen het gemiddeld product van de afwijkingen in x en y in de steekproef. Let op dat we hierbij weer corrigeren voor het aantal vrijheidsgraden. We geven elke observatie geen gewicht van 1/n maar van 1/(n-1). We hebben inderdaad het gemiddelde geschat, hier is dat gemiddelde bivariaat (het heeft een x en y coordinaat).</p>
<p>Deze schatter wordt ook wel de Pearson correlatie genoemd en heeft volgende eigenschappen:</p>
<ul>
<li><p>Er is een positieve correlatie wanneer <span class="math inline">\(y\)</span> gemiddeld toeneemt bij een toename van: <span class="math inline">\(x \ \nearrow \ \Rightarrow \ y \ \nearrow\)</span></p></li>
<li><p>Er is een negatieve correlatie als <span class="math inline">\(y\)</span> gemiddeld afneemt bij een toename in <span class="math inline">\(x\)</span>: <span class="math inline">\(x \ \nearrow \ \Rightarrow \ y \ \searrow\)</span></p></li>
<li><p>De correlatie ligt ook altijd tussen -1 en 1</p></li>
</ul>
<p>In de figuur <a href="chap-describe.html#fig:bijdrageCor">4.7</a> wordt de bijdrage weergegeven van individuele metingen in de correlatie. Als punten in het 1ste en 3de kwadrant liggen is er een negatieve bijdrage van de observatie in de correlatie, als ze in het 2de en 4de kwadrant liggen is er een positieve bijdrage.</p>
<div class="figure"><span id="fig:bijdrageCor"></span>
<img src="Statistiek_2020_2021_files/figure-html/bijdrageCor-1.png" alt="Bijdrage van individuele metingen in de correlatie." width="672" />
<p class="caption">
Figuur 4.7: Bijdrage van individuele metingen in de correlatie.
</p>
</div>
<p>We berekenen vervolgens de correlatie voor lengte, gewicht en het log getransformeerde gewicht.</p>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="chap-describe.html#cb178-1" aria-hidden="true"></a>NHANES<span class="op">%&gt;%</span></span>
<span id="cb178-2"><a href="chap-describe.html#cb178-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">filter</span>(Age <span class="op">&gt;=</span><span class="st"> </span><span class="dv">18</span> <span class="op">&amp;</span><span class="st"> </span>Gender<span class="op">==</span><span class="st">&quot;female&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb178-3"><a href="chap-describe.html#cb178-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">select</span>(Weight,Height) <span class="op">%&gt;%</span></span>
<span id="cb178-4"><a href="chap-describe.html#cb178-4" aria-hidden="true"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">log2Weight=</span>Weight<span class="op">%&gt;%</span>log2) <span class="op">%&gt;%</span></span>
<span id="cb178-5"><a href="chap-describe.html#cb178-5" aria-hidden="true"></a><span class="st">  </span>na.exclude <span class="op">%&gt;%</span></span>
<span id="cb178-6"><a href="chap-describe.html#cb178-6" aria-hidden="true"></a><span class="st">  </span>cor</span></code></pre></div>
<pre><code>##               Weight    Height log2Weight
## Weight     1.0000000 0.2845792  0.9811638
## Height     0.2845792 1.0000000  0.3074578
## log2Weight 0.9811638 0.3074578  1.0000000</code></pre>
<p>Merk op dat:</p>
<ul>
<li>De correlatie lager is als de data niet worden getransformeerd.</li>
<li>De Pearson correlatie is gevoelig voor outliers!</li>
<li>Gebruik de Pearson correlatie niet voor scheef verdeelde data of data met outliers!</li>
</ul>
<div id="impact-van-outliers" class="section level4" number="4.7.2.1">
<h4><span class="header-section-number">4.7.2.1</span> Impact van outliers</h4>
<p>In figuur <a href="chap-describe.html#fig:corOutlier">4.8</a> wordt de impact van outliers op de Pearson correlatie geïllustreerd d.m.v. gesimuleerde data met één outlier. We zien dat de correlatie bijna halveert ten gevolge van de outlier!</p>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb180-1"><a href="chap-describe.html#cb180-1" aria-hidden="true"></a><span class="kw">set.seed</span>(<span class="dv">100</span>)</span>
<span id="cb180-2"><a href="chap-describe.html#cb180-2" aria-hidden="true"></a>x &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">20</span>)</span>
<span id="cb180-3"><a href="chap-describe.html#cb180-3" aria-hidden="true"></a>simData &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">x=</span>x,<span class="dt">y=</span>x<span class="op">*</span><span class="dv">2</span> <span class="op">+</span><span class="st"> </span><span class="kw">rnorm</span>(<span class="kw">length</span>(x)))</span>
<span id="cb180-4"><a href="chap-describe.html#cb180-4" aria-hidden="true"></a>p1 &lt;-<span class="st"> </span>simData <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>x,<span class="dt">y=</span>y)) <span class="op">+</span></span>
<span id="cb180-5"><a href="chap-describe.html#cb180-5" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb180-6"><a href="chap-describe.html#cb180-6" aria-hidden="true"></a><span class="st">  </span><span class="kw">ggtitle</span>(<span class="kw">paste</span>(<span class="st">&quot;cor =&quot;</span>,<span class="kw">cor</span>(simData[,<span class="dv">1</span>],simData[,<span class="dv">2</span>]) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">round</span>(.,<span class="dv">2</span>)))</span>
<span id="cb180-7"><a href="chap-describe.html#cb180-7" aria-hidden="true"></a></span>
<span id="cb180-8"><a href="chap-describe.html#cb180-8" aria-hidden="true"></a>outlier&lt;-<span class="st"> </span><span class="kw">rbind</span>(simData,<span class="kw">c</span>(<span class="dv">2</span>,<span class="op">-</span><span class="dv">4</span>))</span>
<span id="cb180-9"><a href="chap-describe.html#cb180-9" aria-hidden="true"></a>p2 &lt;-<span class="st"> </span>outlier <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>x,<span class="dt">y=</span>y)) <span class="op">+</span></span>
<span id="cb180-10"><a href="chap-describe.html#cb180-10" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb180-11"><a href="chap-describe.html#cb180-11" aria-hidden="true"></a><span class="st">  </span><span class="kw">ggtitle</span>(<span class="kw">paste</span>(<span class="st">&quot;cor =&quot;</span>,<span class="kw">cor</span>(outlier[,<span class="dv">1</span>],outlier[,<span class="dv">2</span>]) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">round</span>(.,<span class="dv">2</span>)))</span>
<span id="cb180-12"><a href="chap-describe.html#cb180-12" aria-hidden="true"></a></span>
<span id="cb180-13"><a href="chap-describe.html#cb180-13" aria-hidden="true"></a><span class="kw">grid.arrange</span>(p1,p2,<span class="dt">ncol=</span><span class="dv">2</span>)</span></code></pre></div>
<div class="figure"><span id="fig:corOutlier"></span>
<img src="Statistiek_2020_2021_files/figure-html/corOutlier-1.png" alt="Correlatie van gesimuleerde data met 1 outlier" width="672" />
<p class="caption">
Figuur 4.8: Correlatie van gesimuleerde data met 1 outlier
</p>
</div>
</div>
<div id="de-pearson-correlatie-pikt-enkel-linear-associatie-op" class="section level4" number="4.7.2.2">
<h4><span class="header-section-number">4.7.2.2</span> De Pearson correlatie pikt enkel linear associatie op</h4>
<p>In figuur <a href="chap-describe.html#fig:corQuad">4.9</a> simuleren we data met een kwadratisch verband en observeren we dat de correlatie bijna nul is!</p>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb181-1"><a href="chap-describe.html#cb181-1" aria-hidden="true"></a>x &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">100</span>)</span>
<span id="cb181-2"><a href="chap-describe.html#cb181-2" aria-hidden="true"></a>quadratic &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">x=</span>x,<span class="dt">y=</span>x<span class="op">^</span><span class="dv">2</span> <span class="op">+</span><span class="st"> </span><span class="kw">rnorm</span>(<span class="kw">length</span>(x)))</span>
<span id="cb181-3"><a href="chap-describe.html#cb181-3" aria-hidden="true"></a>quadratic <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>x,<span class="dt">y=</span>y)) <span class="op">+</span></span>
<span id="cb181-4"><a href="chap-describe.html#cb181-4" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb181-5"><a href="chap-describe.html#cb181-5" aria-hidden="true"></a><span class="st">  </span><span class="kw">ggtitle</span>(<span class="kw">paste</span>(<span class="st">&quot;cor =&quot;</span>,<span class="kw">cor</span>(quadratic[,<span class="dv">1</span>],quadratic[,<span class="dv">2</span>]) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">round</span>(.,<span class="dv">2</span>))) <span class="op">+</span></span>
<span id="cb181-6"><a href="chap-describe.html#cb181-6" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="kw">mean</span>(quadratic[,<span class="dv">2</span>]),<span class="dt">col=</span><span class="st">&quot;red&quot;</span>) <span class="op">+</span></span>
<span id="cb181-7"><a href="chap-describe.html#cb181-7" aria-hidden="true"></a><span class="st">    </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="kw">mean</span>(quadratic[,<span class="dv">1</span>]),<span class="dt">col=</span><span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<div class="figure"><span id="fig:corQuad"></span>
<img src="Statistiek_2020_2021_files/figure-html/corQuad-1.png" alt="Correlatie van gesimuleerde data met een kwadratisch verband. De data in de bovenste kwadranten compenseren elkaar als het ware alsook in de onderste kwadranten (ongeveer evenveel positieve en negatieve bijdragen door de data in de correlatie)" width="672" />
<p class="caption">
Figuur 4.9: Correlatie van gesimuleerde data met een kwadratisch verband. De data in de bovenste kwadranten compenseren elkaar als het ware alsook in de onderste kwadranten (ongeveer evenveel positieve en negatieve bijdragen door de data in de correlatie)
</p>
</div>
</div>
</div>
<div id="verschillende-groottes-van-correlatie" class="section level3" number="4.7.3">
<h3><span class="header-section-number">4.7.3</span> Verschillende groottes van correlatie</h3>
<p>Om een inzicht te krijgen in de grootte van de correlatie, simuleren we data met een verschillende correlatie. We geven telkens de correlatie weer boven de plot. Hoe sterker de correlatie hoe meer de puntenwolk naar een lineair verband toegaat.</p>
<p><img src="Statistiek_2020_2021_files/figure-html/unnamed-chunk-121-1.png" width="672" /><img src="Statistiek_2020_2021_files/figure-html/unnamed-chunk-121-2.png" width="672" /></p>
</div>
<div id="spearman-correlatie" class="section level3" number="4.7.4">
<h3><span class="header-section-number">4.7.4</span> Spearman correlatie</h3>
<p>De Spearman correlatie is de Pearson correlatie na transformatie van de data naar ranks. Hierdoor wordt deze schatter minder gevoelig voor outliers.</p>
<ul>
<li>Pearson correlatie</li>
</ul>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb182-1"><a href="chap-describe.html#cb182-1" aria-hidden="true"></a><span class="kw">cor</span>(outlier)</span></code></pre></div>
<pre><code>##           x         y
## x 1.0000000 0.4682823
## y 0.4682823 1.0000000</code></pre>
<ul>
<li>Spearman correlatie</li>
</ul>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb184-1"><a href="chap-describe.html#cb184-1" aria-hidden="true"></a><span class="kw">cor</span>(outlier,<span class="dt">method=</span><span class="st">&quot;spearman&quot;</span>)</span></code></pre></div>
<pre><code>##           x         y
## x 1.0000000 0.6571429
## y 0.6571429 1.0000000</code></pre>
<p>We verifiëren dat de Spearman correlatie de Pearson correlatie is van rang getransformeerde data. Die wordt bekomen door de observaties te ordenen van klein naar groot en elke observatie te vervangen door zijn rangorde.</p>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb186-1"><a href="chap-describe.html#cb186-1" aria-hidden="true"></a>rankData&lt;-<span class="kw">apply</span>(outlier,<span class="dv">2</span>,rank)</span>
<span id="cb186-2"><a href="chap-describe.html#cb186-2" aria-hidden="true"></a><span class="kw">cor</span>(rankData)</span></code></pre></div>
<pre><code>##           x         y
## x 1.0000000 0.6571429
## y 0.6571429 1.0000000</code></pre>
<p>We berekenen nu de Spearman correlatie in de NHANES studie.
We observeren dat de correlatie tussen lengte en gewicht, en lengte en log2 getransformeerd gewicht exact gelijk is.
Dat is logisch want de log-transformatie is een monotone transformatie en verandert de ordening van de data dus niet, de ranks van gewicht en deze van het log gewicht zijn identiek!</p>
<div class="sourceCode" id="cb188"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb188-1"><a href="chap-describe.html#cb188-1" aria-hidden="true"></a>NHANES<span class="op">%&gt;%</span></span>
<span id="cb188-2"><a href="chap-describe.html#cb188-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">filter</span>(Age <span class="op">&gt;=</span><span class="st"> </span><span class="dv">18</span> <span class="op">&amp;</span><span class="st"> </span>Gender<span class="op">==</span><span class="st">&quot;female&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb188-3"><a href="chap-describe.html#cb188-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">select</span>(Weight,Height) <span class="op">%&gt;%</span></span>
<span id="cb188-4"><a href="chap-describe.html#cb188-4" aria-hidden="true"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">log2Weight=</span>Weight<span class="op">%&gt;%</span>log2) <span class="op">%&gt;%</span></span>
<span id="cb188-5"><a href="chap-describe.html#cb188-5" aria-hidden="true"></a><span class="st">  </span>na.exclude <span class="op">%&gt;%</span></span>
<span id="cb188-6"><a href="chap-describe.html#cb188-6" aria-hidden="true"></a><span class="st">  </span><span class="kw">cor</span>(<span class="dt">method=</span><span class="st">&quot;spearman&quot;</span>)</span></code></pre></div>
<pre><code>##               Weight    Height log2Weight
## Weight     1.0000000 0.2892776  1.0000000
## Height     0.2892776 1.0000000  0.2892776
## log2Weight 1.0000000 0.2892776  1.0000000</code></pre>
<p>Bij het interpreteren van correlaties, alsook bij het uitvoeren van
regressie-analyses in de volgende secties, zijn de volgende waarschuwingen
van zeer groot belang:</p>
<ol style="list-style-type: decimal">
<li><p>Correlaties zijn het makkelijkst te interpreteren tussen 2 groepen Normaal verdeelde observaties. Een kleine training laat immers toe om snel inzicht te krijgen in de grootte van de correlatiecoëfficiënt zonder zich verder over de specifieke verdeling te hoeven bekommeren. In het bijzonder kan men voor Normaal verdeelde observaties visueel inzicht krijgen in de sterkte van de correlatie door een ellips rond de puntenwolk te tekenen die (nagenoeg) alle punten bevat. Als de ellips op een cirkel lijkt, dan is er geen correlatie. Hoe dunner de ellips, hoe sterker de correlatie. De oriëntatie van de ellips geeft hierbij het teken van de correlatie weer.</p></li>
<li><p>Voor niet-Normale gegevens hangt de betekenis van een correlatiecoëfficiënt van zekere grootte, nauw samen met de specifieke vorm van de verdeling. Wanneer de 2 variabelen die we onderzoeken niet Normaal verdeeld zijn, dan zijn er 2 mogelijkheden om een zinvolle correlatiecoëfficiënt weer te geven. Variabelen die scheef verdeeld zijn, kan men transformeren (bvb. een log-transformatie) in de hoop dat de getransformeerde gegevens bij benadering Normaal verdeeld zijn en lineair samenhangen.</p></li>
<li><p>Merk op dat een correlatiecoëfficiënt van 0 tussen 2 variabelen <span class="math inline">\(X\)</span> en <span class="math inline">\(Y\)</span> niet noodzakelijk impliceert dat deze variabelen onafhankelijk zijn. Zie kwadratisch verband! Daarom is het van belang om de aard van samenhang tussen 2 variabelen steeds te onderzoeken via een scatterplot alvorens een correlatiecoëfficiënt te rapporteren. Wanneer het verband monotoon is, maar sterk niet-lineair is, dan is het aangewezen om niet de Pearson correlatiecoëfficiënt, maar Spearman’s correlatiecoëfficiënt te rapporteren. Indien het verband niet-monotoon is, dan zijn correlatiecoëfficiënten niet geschikt en moet men overstappen op meer geavanceerde regressietechnieken.</p></li>
<li><p>Bij jonge kinderen is de grootte van hun schoenmaat uiteraard sterk gecorreleerd met hun leescapaciteiten. Dat op zich impliceert echter niet dat het leren van nieuwe woorden hun voeten doet groeien of dat het groeien van hun voeten impliceert dat ze beter kunnen lezen. Ook algemeen<a href="#fn21" class="footnote-ref" id="fnref21"><sup>21</sup></a> hoeft een correlatie tussen 2 variabelen niet te impliceren dat er een causaal verband is. De relatie tussen 2 metingen kan immers sterk verstoord worden door confounders (bvb. de leeftijd in bovenstaand voorbeeld). Hoewel dit overduidelijk is in bovenstaand voorbeeld, is het in vele andere contexten veel minder duidelijk en worden er, vooral in de populaire literatuur, vaak causale beweringen gemaakt die niet (volledig) door de gegevens worden gestaafd. Volgend voorbeeld illustreert dit. Denk hierbij aan het voorbeeld van de associatie van groente consumptie en covid mortaliteit.</p></li>
<li><p>Een <em>ecologische analyse</em> is een statistische analyse waarbij men associaties bestudeert tussen samenvattingsmaten (zoals gemiddelden, incidenties, …) die reeds berekend werden voor groepen subjecten. Dit is het geval bij het covid voorbeeld uit de introductie waarbij men mortaliteit modellereert in functie van de gemiddelde dagelijkse groenteconsumptie per capita in verschillende landen. Wanneer men aldus een <em>ecologische correlatie</em> vaststelt voor groepen subjecten of individuen (in dit geval,landen), impliceert dat niet noodzakelijk dat deze correlatie ook voor de subjecten zelf opgaat<a href="#fn22" class="footnote-ref" id="fnref22"><sup>22</sup></a>. Volgend voorbeeld illustreert dit.</p></li>
</ol>

<div class="example">
<span id="exm:unnamed-chunk-126" class="example"><strong>Voorbeeld 4.4  (Ecological fallacy)  </strong></span>
</div>
<p>Voor de 48 staten in de V.S. werden telkens 2 getallen
berekend: het percentage van de mensen die in een ander land geboren zijn en het percentage geletterden. De correlatie ertussen bedraagt 0.53 (Robinson, 1950). Dit is een <em>ecologische correlatie</em> omdat de eenheid van de analyse de groep residenten uit een zelfde staat is, en niet de individuele residenten zelf. Deze ecologische correlatie suggereert dat mensen van vreemde afkomst doorgaans beter geschoold zijn (in Amerikaans Engels) dan de oorspronkelijke inwoners. Wanneer men echter de correlatie berekent op basis
van de gegevens voor alle individuele residenten, bekomt men -0.11. De ecologische analyse is hier duidelijk misleidend: het teken van de correlatie is er positief omdat mensen van vreemde origine de neiging hebben om te gaan wonen in staten waar de oorspronkelijke bevolking relatief goed geschoold is.</p>
<p><strong>Einde voorbeeld</strong></p>
</div>
</div>
<div id="sec:missing" class="section level2" number="4.8">
<h2><span class="header-section-number">4.8</span> Onvolledige gegevens</h2>
<p>Het gebeurt vaak in de biowetenschappen dat, ondanks zorgvuldig veld- en laboratoriumwerk, metingen die men plande te verzamelen, niet bekomen werden. Men noemt deze dan <em>ontbrekende gegevens</em> of <em>missing data (points)</em>.</p>
<p>Minder drastisch, kunnen observaties soms slechts ten dele gekend zijn.
Bijvoorbeeld bij een studie van de overlevingsduur van dieren en planten wacht men niet steeds tot
alle subjecten gestorven zijn. Op het eind van de studie zal men bijvoorbeeld voor een 50-jarige
olifant die in leven is, slechts weten dat de overlevingstijd
minstens 50 jaar bedraagt, maar niet de exacte waarde kennen. Zo’n gegeven
wordt <em>rechts-gecensureerd</em> genoemd: we weten dat de gewenste
observatie rechts van 50 ligt, maar verder niets meer.</p>
<p>Analoog kunnen observaties <em>links-gecensureerd</em> zijn. Bij het meten
van bepaalde concentraties kan een detectielimiet bestaan: een ondergrens beneden
dewelke het meettoestel geen aanwezigheid kan detecteren. Men weet in zo’n
geval dat de concentratie kleiner dan die ondergrens is, maar niet hoeveel
kleiner.</p>
<p>Tenslotte vermelden we nog <em>interval-gecensureerde</em> gegevens. Bij het
screenen naar HIV bijvoorbeeld, zal men weten dat een subject seropositief
geworden is ergens tussen de laatste negatieve HIV test en de eerste
positieve HIV test, maar het exacte tijdstip van seroconversie blijft
onbekend.</p>
<p>De aanwezigheid van gegevens die niet of slechts partieel zijn opgemeten zorgt
altijd voor extra moeilijkheden bij de analyse en interpretatie van de
onderzoeksresultaten. Dat is omdat de missende gegevens mogelijks afkomstig zijn
van een speciale populatie. Dat is het meest duidelijk in klinische experimenten bij mensen.
Patiënten zullen hier vaak de studie verlaten wanneer
ze genezen zijn, in welk geval men de metingen van deze patiënten niet te
zien krijgt. Dit negeren door enkel de aanwezige gegevens te analyseren, zal
de resultaten er slechter doen uitzien dan ze in werkelijkheid zijn. Meestal
houdt dat immers de veronderstelling in dat de aanwezige gegevens representatief blijven
voor de populatie die men wenst te bestuderen. Dit kan in sommige gevallen
de resultaten sterk vertekenen. In de statistische literatuur zijn de
laatste jaren heel wat complexe technieken ontwikkeld om hiervoor te
corrigeren. Deze technieken worden meer en meer in de statistische software
ingebouwd en recent heeft ook R verschillende bibliotheken toegevoegd.
Het is
echter aangewezen om voor het gebruik van deze gevorderde technieken een
statisticus te consulteren.</p>
</div>
<div id="clips-over-de-code-in-dit-hoofdstuk" class="section level2" number="4.9">
<h2><span class="header-section-number">4.9</span> Clips over de code in dit hoofdstuk</h2>
<ol style="list-style-type: decimal">
<li>Univariate exploratie van continue variabelen</li>
</ol>
<iframe width="560" height="315" src="https://www.youtube.com/embed/Du4q0yatlmA" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen>
</iframe>
<ol start="2" style="list-style-type: decimal">
<li>Beschrijvende statistiek</li>
</ol>
<iframe width="560" height="315" src="https://www.youtube.com/embed/b3CMvj5pMy4" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen>
</iframe>
<ol start="3" style="list-style-type: decimal">
<li>Normale benadering</li>
</ol>
<iframe width="560" height="315" src="https://www.youtube.com/embed/sGSyd-g-Nz0" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen>
</iframe>
<ol start="4" style="list-style-type: decimal">
<li>Associatie van twee continue Variabelen</li>
</ol>
<iframe width="560" height="315" src="https://www.youtube.com/embed/pnbf-MhCX3U" frameborder="0" style="display: block; margin: auto;" allow="autoplay; encrypted-media" allowfullscreen>
</iframe>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="16">
<li id="fn16"><p>Zie Sectie <a href="chap-describe.html#sec:qq">4.4.1</a>.<a href="chap-describe.html#fnref16" class="footnote-back">↩︎</a></p></li>
<li id="fn17"><p>Later zullen we zien dat het nog iets correcter is om te stellen dat 95% van de waarnemingen liggen tussen <span class="math inline">\(\bar{x} - 1.96 s_x\)</span> en <span class="math inline">\(\bar{x} + 1.96 s_x\)</span>.<a href="chap-describe.html#fnref17" class="footnote-back">↩︎</a></p></li>
<li id="fn18"><p>Merk op dat dit design niet optimaal is omdat replicaties op de verkeerde schaal werden bekomen. Idealiter moesten meer dan 2 stukken grond in de studie opgenomen worden omdat de 2 gekozen stukken grond in veel meer kunnen verschillen dan alleen het bodemtype. Verschillen in de verdeling van houtluizen kunnen bijgevolg niet zomaar aan het bodemtype kunnen toegeschreven worden.<a href="chap-describe.html#fnref18" class="footnote-back">↩︎</a></p></li>
<li id="fn19"><p>Al is het nog de vraag of die associatie toevallig is, dan wel systematisch. We komen in het hoofdstuk <a href="chap-categorisch.html#chap:categorisch">9</a>. terug op technieken om dit te onderzoeken.<a href="chap-describe.html#fnref19" class="footnote-back">↩︎</a></p></li>
<li id="fn20"><p>Dit is bijvoorbeeld het geval in logistische regressiemodellen die gebruikt worden om het
risico op een bepaalde aandoening te modelleren in functie van prognostische
factoren.<a href="chap-describe.html#fnref20" class="footnote-back">↩︎</a></p></li>
<li id="fn21"><p>In het Engels is dit welbekend onder de zinsnede <em>`Association is not causation!’</em>.<a href="chap-describe.html#fnref21" class="footnote-back">↩︎</a></p></li>
<li id="fn22"><p>In het Engels is dit welbekend onder de naam <em>`ecological fallacy’</em>.<a href="chap-describe.html#fnref22" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="chap-design.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="chap-besluit.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/04-DataExploratie.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Statistiek_2020_2021.pdf", "Statistiek_2020_2021.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
